-- =====================================================================
-- VERIFICACAO: as 123 migrations de supabase/migrations/ estao aplicadas?
--
-- Gerado a partir do conteudo REAL dos arquivos do repo (branch
-- claude/debug-console-error-FWrLE). O manifesto abaixo tem 1160
-- declaracoes de CREATE/ALTER extraidas dos 123 arquivos, que somam
-- 926 objetos distintos: 137 tabelas, 98 funcoes, 294 colunas
-- adicionadas via ALTER TABLE e 397 indices. (1160 > 926 porque varias
-- migrations recriam o mesmo objeto com IF NOT EXISTS — por isso o
-- resumo conta objeto unico e o status por migration conta declaracao.)
--
-- Cobertura: 115 dos 123 arquivos aparecem no BLOCO 2. Os 8 restantes
-- nao criam objeto nenhum e por isso tem teste proprio no BLOCO 3.
--
-- POR QUE NAO OLHAR supabase_migrations.schema_migrations:
--   aquela tabela so registra o que passou pelo CLI. Este repo tem
--   arquivos chamados PARTE1_tabelas_ads.sql, whatsapp-migration-fix.sql,
--   flow-builder-v3-complete.sql — nomes que o CLI nao aceita. Boa parte
--   foi colada a mao no SQL Editor e nunca foi registrada. A unica prova
--   confiavel e perguntar ao catalogo se o objeto existe.
--
-- 100% SOMENTE LEITURA. Nao cria, nao altera, nao apaga nada.
--
-- COMO RODAR: cole o arquivo inteiro no SQL Editor do Supabase e execute.
-- Sao 3 blocos independentes; pode rodar um de cada vez.
-- =====================================================================


-- ---------------------------------------------------------------------
-- BLOCO 1 - O que o CLI acha que aplicou (contexto, nao veredito)
--
-- Se a tabela nao existir, a resposta e "o CLI nunca gerenciou este
-- projeto" — o que ja explica muita coisa. Se existir, compare o total
-- com os 123 arquivos do repo.
-- ---------------------------------------------------------------------
-- Em DO block de proposito: se a tabela nao existir, um SELECT direto
-- levanta 42P01 e o SQL Editor aborta os blocos seguintes junto. Aqui a
-- ausencia vira mensagem, nao erro.
DO $$
DECLARE n int; mn text; mx text;
BEGIN
  IF to_regclass('supabase_migrations.schema_migrations') IS NULL THEN
    RAISE NOTICE '--> schema_migrations NAO EXISTE.';
    RAISE NOTICE '    Nenhuma migration passou pelo CLI. O BLOCO 2 e a unica fonte de verdade.';
  ELSE
    EXECUTE 'SELECT count(*), min(version)::text, max(version)::text
               FROM supabase_migrations.schema_migrations'
      INTO n, mn, mx;
    RAISE NOTICE '--> schema_migrations: % registradas (repo tem 123 arquivos)', n;
    RAISE NOTICE '    primeira: %  |  ultima: %', coalesce(mn,'-'), coalesce(mx,'-');
    IF n < 123 THEN
      RAISE NOTICE '    Menos que 123: o resto foi aplicado a mao. Confie no BLOCO 2.';
    END IF;
  END IF;
END $$;


-- ---------------------------------------------------------------------
-- BLOCO 2 - O VEREDITO
--
-- Confere objeto por objeto contra o catalogo e devolve, em uma tabela:
--   secao 1  resumo por tipo de objeto
--   secao 2  cada migration com status APLICADA / PARCIAL / NAO_APLICADA
--   secao 3  cada objeto que esta faltando, e em que arquivo nasceu
-- ---------------------------------------------------------------------
WITH esperado(arquivo, tipo, obj) AS (VALUES
  ('001_enable_rls.sql','f','auth.is_org_admin'),
  ('001_enable_rls.sql','f','auth.organization_id'),
  ('001_enable_rls.sql','f','public.create_org_policies'),
  ('001_enable_rls.sql','f','public.set_organization_id'),
  ('002_fix_update_policies.sql','f','public.fix_update_policy'),
  ('20260108_automation_triggers.sql','t','public.event_logs'),
  ('20260108_automation_triggers.sql','f','public.emit_automation_event'),
  ('20260108_automation_triggers.sql','f','public.find_matching_automations'),
  ('20260108_automation_triggers.sql','f','public.trigger_contact_created'),
  ('20260108_automation_triggers.sql','f','public.trigger_deal_created'),
  ('20260108_automation_triggers.sql','f','public.trigger_deal_lost'),
  ('20260108_automation_triggers.sql','f','public.trigger_deal_stage_changed'),
  ('20260108_automation_triggers.sql','f','public.trigger_deal_won'),
  ('20260108_automation_triggers.sql','f','public.trigger_tag_added'),
  ('20260108_automation_triggers.sql','c','automation_runs.current_node_id'),
  ('20260108_automation_triggers.sql','c','automation_runs.last_error'),
  ('20260108_automation_triggers.sql','c','automation_runs.retry_count'),
  ('20260108_automation_triggers.sql','c','automation_runs.trigger_event_id'),
  ('20260108_automation_triggers.sql','c','automation_runs.waiting_until'),
  ('20260108_automation_triggers.sql','i','idx_event_logs_created'),
  ('20260108_automation_triggers.sql','i','idx_event_logs_org'),
  ('20260108_automation_triggers.sql','i','idx_event_logs_processed'),
  ('20260108_automation_triggers.sql','i','idx_event_logs_type'),
  ('20260108_automation_triggers_v2.sql','t','public.event_logs'),
  ('20260108_automation_triggers_v2.sql','f','public.emit_automation_event'),
  ('20260108_automation_triggers_v2.sql','f','public.find_matching_automations'),
  ('20260108_automation_triggers_v2.sql','f','public.trigger_contact_created'),
  ('20260108_automation_triggers_v2.sql','f','public.trigger_deal_created'),
  ('20260108_automation_triggers_v2.sql','f','public.trigger_deal_lost'),
  ('20260108_automation_triggers_v2.sql','f','public.trigger_deal_stage_changed'),
  ('20260108_automation_triggers_v2.sql','f','public.trigger_deal_won'),
  ('20260108_automation_triggers_v2.sql','f','public.trigger_tag_added'),
  ('20260108_automation_triggers_v2.sql','c','automation_runs.current_node_id'),
  ('20260108_automation_triggers_v2.sql','c','automation_runs.last_error'),
  ('20260108_automation_triggers_v2.sql','c','automation_runs.retry_count'),
  ('20260108_automation_triggers_v2.sql','c','automation_runs.trigger_event_id'),
  ('20260108_automation_triggers_v2.sql','c','automation_runs.waiting_until'),
  ('20260108_automation_triggers_v2.sql','c','event_logs.error_message'),
  ('20260108_automation_triggers_v2.sql','c','event_logs.processed'),
  ('20260108_automation_triggers_v2.sql','c','event_logs.processed_at'),
  ('20260108_automation_triggers_v2.sql','c','event_logs.source'),
  ('20260108_automation_triggers_v2.sql','i','idx_event_logs_created'),
  ('20260108_automation_triggers_v2.sql','i','idx_event_logs_org'),
  ('20260108_automation_triggers_v2.sql','i','idx_event_logs_processed'),
  ('20260108_automation_triggers_v2.sql','i','idx_event_logs_type'),
  ('20260108_flow_webhooks.sql','t','public.credentials'),
  ('20260108_flow_webhooks.sql','t','public.flow_webhook_logs'),
  ('20260108_flow_webhooks.sql','t','public.flow_webhooks'),
  ('20260108_flow_webhooks.sql','f','public.update_webhook_stats'),
  ('20260108_flow_webhooks.sql','i','idx_credentials_org'),
  ('20260108_flow_webhooks.sql','i','idx_credentials_type'),
  ('20260108_flow_webhooks.sql','i','idx_flow_webhook_logs_received'),
  ('20260108_flow_webhooks.sql','i','idx_flow_webhook_logs_webhook'),
  ('20260108_flow_webhooks.sql','i','idx_flow_webhooks_automation'),
  ('20260108_flow_webhooks.sql','i','idx_flow_webhooks_org'),
  ('20260108_flow_webhooks.sql','i','idx_flow_webhooks_token'),
  ('20260110_orders_and_extra_triggers.sql','t','public.abandoned_carts'),
  ('20260110_orders_and_extra_triggers.sql','t','public.orders'),
  ('20260110_orders_and_extra_triggers.sql','f','public.check_contact_dates'),
  ('20260110_orders_and_extra_triggers.sql','f','public.emit_date_events'),
  ('20260110_orders_and_extra_triggers.sql','f','public.find_matching_automations'),
  ('20260110_orders_and_extra_triggers.sql','f','public.trigger_cart_abandoned'),
  ('20260110_orders_and_extra_triggers.sql','f','public.trigger_order_created'),
  ('20260110_orders_and_extra_triggers.sql','f','public.trigger_order_paid'),
  ('20260110_orders_and_extra_triggers.sql','c','contacts.birth_date'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_abandoned_at'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_abandoned_contact'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_abandoned_org'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_abandoned_status'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_contacts_birth_date'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_orders_contact'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_orders_created'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_orders_external'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_orders_financial'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_orders_org'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_orders_status'),
  ('20260110_orders_and_extra_triggers.sql','i','idx_orders_store'),
  ('20260111_shopify_import_jobs.sql','t','public.shopify_import_jobs'),
  ('20260111_shopify_import_jobs.sql','i','idx_import_jobs_org'),
  ('20260111_shopify_import_jobs.sql','i','idx_import_jobs_pending'),
  ('20260111_shopify_import_jobs.sql','i','idx_import_jobs_status'),
  ('20260111_shopify_import_jobs.sql','i','idx_import_jobs_store'),
  ('20260111_shopify_sync_automation.sql','t','public.shopify_automation_logs'),
  ('20260111_shopify_sync_automation.sql','t','public.shopify_sync_config'),
  ('20260111_shopify_sync_automation.sql','t','public.shopify_transition_rules'),
  ('20260111_shopify_sync_automation.sql','f','public.update_updated_at_column'),
  ('20260111_shopify_sync_automation.sql','i','idx_automation_logs_contact'),
  ('20260111_shopify_sync_automation.sql','i','idx_automation_logs_created'),
  ('20260111_shopify_sync_automation.sql','i','idx_automation_logs_rule'),
  ('20260111_shopify_sync_automation.sql','i','idx_automation_logs_store'),
  ('20260111_shopify_sync_automation.sql','i','idx_sync_config_org'),
  ('20260111_shopify_sync_automation.sql','i','idx_sync_config_store'),
  ('20260111_shopify_sync_automation.sql','i','idx_transition_rules_active'),
  ('20260111_shopify_sync_automation.sql','i','idx_transition_rules_org'),
  ('20260111_shopify_sync_automation.sql','i','idx_transition_rules_store'),
  ('20260111_shopify_sync_automation.sql','i','idx_transition_rules_trigger'),
  ('20260113_create_ai_message_logs.sql','t','public.ai_message_logs'),
  ('20260113_create_ai_message_logs.sql','i','idx_ai_message_logs_conversation'),
  ('20260113_create_ai_message_logs.sql','i','idx_ai_message_logs_created'),
  ('20260113_create_ai_message_logs.sql','i','idx_ai_message_logs_organization'),
  ('20260114_add_store_id_to_automation_rules.sql','c','automation_rules.store_id'),
  ('20260114_add_store_id_to_automation_rules.sql','i','idx_automation_rules_store'),
  ('20260123_ads_and_help_tables.sql','t','public.abandoned_carts'),
  ('20260123_ads_and_help_tables.sql','t','public.credentials'),
  ('20260123_ads_and_help_tables.sql','t','public.faq_items'),
  ('20260123_ads_and_help_tables.sql','t','public.google_ads_accounts'),
  ('20260123_ads_and_help_tables.sql','t','public.google_ads_ad_groups'),
  ('20260123_ads_and_help_tables.sql','t','public.google_ads_campaigns'),
  ('20260123_ads_and_help_tables.sql','t','public.google_ads_keywords'),
  ('20260123_ads_and_help_tables.sql','t','public.google_ads_metrics'),
  ('20260123_ads_and_help_tables.sql','t','public.google_ads_product_metrics'),
  ('20260123_ads_and_help_tables.sql','t','public.google_ads_products'),
  ('20260123_ads_and_help_tables.sql','t','public.google_ads_search_terms'),
  ('20260123_ads_and_help_tables.sql','t','public.help_articles'),
  ('20260123_ads_and_help_tables.sql','t','public.help_categories'),
  ('20260123_ads_and_help_tables.sql','t','public.meta_ads_accounts'),
  ('20260123_ads_and_help_tables.sql','t','public.meta_ads_ads'),
  ('20260123_ads_and_help_tables.sql','t','public.meta_ads_adsets'),
  ('20260123_ads_and_help_tables.sql','t','public.meta_ads_campaigns'),
  ('20260123_ads_and_help_tables.sql','t','public.meta_ads_metrics'),
  ('20260123_ads_and_help_tables.sql','t','public.notifications'),
  ('20260123_ads_and_help_tables.sql','t','public.orders'),
  ('20260123_ads_and_help_tables.sql','t','public.tiktok_ads_accounts'),
  ('20260123_ads_and_help_tables.sql','t','public.tiktok_ads_adgroups'),
  ('20260123_ads_and_help_tables.sql','t','public.tiktok_ads_campaigns'),
  ('20260123_ads_and_help_tables.sql','t','public.tiktok_ads_metrics'),
  ('20260123_ads_and_help_tables.sql','i','idx_abandoned_carts_contact'),
  ('20260123_ads_and_help_tables.sql','i','idx_abandoned_carts_org'),
  ('20260123_ads_and_help_tables.sql','i','idx_abandoned_carts_status'),
  ('20260123_ads_and_help_tables.sql','i','idx_credentials_org_type'),
  ('20260123_ads_and_help_tables.sql','i','idx_faq_items_category'),
  ('20260123_ads_and_help_tables.sql','i','idx_google_ads_metrics_campaign'),
  ('20260123_ads_and_help_tables.sql','i','idx_google_ads_metrics_org_date'),
  ('20260123_ads_and_help_tables.sql','i','idx_help_articles_category'),
  ('20260123_ads_and_help_tables.sql','i','idx_help_articles_search'),
  ('20260123_ads_and_help_tables.sql','i','idx_help_articles_status'),
  ('20260123_ads_and_help_tables.sql','i','idx_meta_ads_metrics_org_date'),
  ('20260123_ads_and_help_tables.sql','i','idx_notifications_org'),
  ('20260123_ads_and_help_tables.sql','i','idx_notifications_user'),
  ('20260123_ads_and_help_tables.sql','i','idx_orders_contact'),
  ('20260123_ads_and_help_tables.sql','i','idx_orders_external'),
  ('20260123_ads_and_help_tables.sql','i','idx_orders_org'),
  ('20260123_ads_and_help_tables.sql','i','idx_orders_status'),
  ('20260123_ads_and_help_tables.sql','i','idx_tiktok_ads_metrics_org_date'),
  ('20260224_crm_forms_and_events.sql','t','public.crm_form_event_logs'),
  ('20260224_crm_forms_and_events.sql','t','public.crm_form_events'),
  ('20260224_crm_forms_and_events.sql','t','public.crm_form_fields'),
  ('20260224_crm_forms_and_events.sql','t','public.crm_form_submissions'),
  ('20260224_crm_forms_and_events.sql','t','public.crm_forms'),
  ('20260224_crm_forms_and_events.sql','t','public.google_ads_accounts'),
  ('20260224_crm_forms_and_events.sql','f','public.increment_form_submissions'),
  ('20260224_crm_forms_and_events.sql','f','public.increment_form_views'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_event_logs_event'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_event_logs_form'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_event_logs_org'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_event_logs_status'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_events_active'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_events_form'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_fields_form'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_fields_position'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_submissions_contact'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_submissions_created'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_submissions_deal'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_submissions_form'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_submissions_org'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_form_submissions_status'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_forms_org'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_forms_org_slug'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_forms_pipeline'),
  ('20260224_crm_forms_and_events.sql','i','idx_crm_forms_status'),
  ('20260224_crm_forms_and_events.sql','i','idx_google_ads_accounts_org'),
  ('20260225_crm_forms_add_store_id.sql','c','crm_forms.store_id'),
  ('20260225_crm_forms_add_store_id.sql','i','idx_crm_forms_org_store'),
  ('20260225_crm_forms_add_store_id.sql','i','idx_crm_forms_store'),
  ('20260225_crm_forms_complete.sql','t','public.crm_form_event_logs'),
  ('20260225_crm_forms_complete.sql','t','public.crm_form_events'),
  ('20260225_crm_forms_complete.sql','t','public.crm_form_fields'),
  ('20260225_crm_forms_complete.sql','t','public.crm_form_submissions'),
  ('20260225_crm_forms_complete.sql','t','public.crm_forms'),
  ('20260225_crm_forms_complete.sql','t','public.google_ads_accounts'),
  ('20260225_crm_forms_complete.sql','f','public.increment_form_submissions'),
  ('20260225_crm_forms_complete.sql','f','public.increment_form_views'),
  ('20260225_crm_forms_complete.sql','f','public.update_crm_forms_updated_at'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_event_logs_event'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_event_logs_form'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_event_logs_org'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_event_logs_status'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_events_active'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_events_form'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_fields_form'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_fields_position'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_submissions_contact'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_submissions_created'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_submissions_deal'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_submissions_form'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_submissions_org'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_form_submissions_status'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_forms_org'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_forms_org_slug'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_forms_pipeline'),
  ('20260225_crm_forms_complete.sql','i','idx_crm_forms_status'),
  ('20260225_crm_forms_complete.sql','i','idx_google_ads_accounts_org'),
  ('20260225_instagram_direct.sql','t','public.instagram_accounts'),
  ('20260225_instagram_direct.sql','t','public.instagram_contacts'),
  ('20260225_instagram_direct.sql','t','public.instagram_conversations'),
  ('20260225_instagram_direct.sql','t','public.instagram_messages'),
  ('20260225_instagram_direct.sql','t','public.instagram_quick_replies'),
  ('20260225_instagram_direct.sql','t','public.oauth_states'),
  ('20260225_instagram_direct.sql','f','public.cleanup_expired_oauth_states'),
  ('20260225_instagram_direct.sql','f','public.update_instagram_account_stats'),
  ('20260225_instagram_direct.sql','f','public.update_instagram_conversation_on_message'),
  ('20260225_instagram_direct.sql','f','public.upsert_instagram_conversation'),
  ('20260225_instagram_direct.sql','i','idx_instagram_accounts_org'),
  ('20260225_instagram_direct.sql','i','idx_instagram_accounts_status'),
  ('20260225_instagram_direct.sql','i','idx_instagram_accounts_store'),
  ('20260225_instagram_direct.sql','i','idx_instagram_contacts_crm'),
  ('20260225_instagram_direct.sql','i','idx_instagram_contacts_org'),
  ('20260225_instagram_direct.sql','i','idx_instagram_contacts_user'),
  ('20260225_instagram_direct.sql','i','idx_instagram_contacts_username'),
  ('20260225_instagram_direct.sql','i','idx_instagram_conversations_account'),
  ('20260225_instagram_direct.sql','i','idx_instagram_conversations_assigned'),
  ('20260225_instagram_direct.sql','i','idx_instagram_conversations_contact'),
  ('20260225_instagram_direct.sql','i','idx_instagram_conversations_last_msg'),
  ('20260225_instagram_direct.sql','i','idx_instagram_conversations_org'),
  ('20260225_instagram_direct.sql','i','idx_instagram_conversations_participant'),
  ('20260225_instagram_direct.sql','i','idx_instagram_conversations_status'),
  ('20260225_instagram_direct.sql','i','idx_instagram_conversations_unified'),
  ('20260225_instagram_direct.sql','i','idx_instagram_messages_account'),
  ('20260225_instagram_direct.sql','i','idx_instagram_messages_conversation'),
  ('20260225_instagram_direct.sql','i','idx_instagram_messages_direction'),
  ('20260225_instagram_direct.sql','i','idx_instagram_messages_msg_id'),
  ('20260225_instagram_direct.sql','i','idx_instagram_messages_org'),
  ('20260225_instagram_direct.sql','i','idx_instagram_messages_timestamp'),
  ('20260225_instagram_direct.sql','i','idx_instagram_quick_replies_org'),
  ('20260225_instagram_direct.sql','i','idx_oauth_states_expires'),
  ('20260225_instagram_direct.sql','i','idx_oauth_states_token'),
  ('20260307_crm_advanced_features.sql','t','public.chat_templates'),
  ('20260307_crm_advanced_features.sql','t','public.crm_analytics_cache'),
  ('20260307_crm_advanced_features.sql','t','public.deal_stage_history'),
  ('20260307_crm_advanced_features.sql','t','public.lead_distribution_rules'),
  ('20260307_crm_advanced_features.sql','t','public.lead_scores'),
  ('20260307_crm_advanced_features.sql','t','public.nps_responses'),
  ('20260307_crm_advanced_features.sql','t','public.nps_surveys'),
  ('20260307_crm_advanced_features.sql','t','public.sla_configs'),
  ('20260307_crm_advanced_features.sql','t','public.sla_metrics'),
  ('20260307_crm_advanced_features.sql','f','public.calculate_deal_stage_time'),
  ('20260307_crm_advanced_features.sql','f','public.distribute_lead_round_robin'),
  ('20260307_crm_advanced_features.sql','f','public.update_nps_stats'),
  ('20260307_crm_advanced_features.sql','c','contacts.assigned_to'),
  ('20260307_crm_advanced_features.sql','c','contacts.last_activity_at'),
  ('20260307_crm_advanced_features.sql','c','contacts.lead_score'),
  ('20260307_crm_advanced_features.sql','c','contacts.purchase_intent'),
  ('20260307_crm_advanced_features.sql','c','deals.source'),
  ('20260307_crm_advanced_features.sql','c','deals.stage_entered_at'),
  ('20260307_crm_advanced_features.sql','c','deals.time_in_current_stage_seconds'),
  ('20260307_crm_advanced_features.sql','c','deals.utm_campaign'),
  ('20260307_crm_advanced_features.sql','c','deals.utm_medium'),
  ('20260307_crm_advanced_features.sql','c','deals.utm_source'),
  ('20260307_crm_advanced_features.sql','c','inbox_conversations.first_response_at'),
  ('20260307_crm_advanced_features.sql','c','inbox_conversations.priority'),
  ('20260307_crm_advanced_features.sql','c','inbox_conversations.sla_breached'),
  ('20260307_crm_advanced_features.sql','c','inbox_conversations.sla_config_id'),
  ('20260307_crm_advanced_features.sql','i','idx_chat_templates_category'),
  ('20260307_crm_advanced_features.sql','i','idx_chat_templates_org'),
  ('20260307_crm_advanced_features.sql','i','idx_crm_analytics_org_date'),
  ('20260307_crm_advanced_features.sql','i','idx_deal_stage_history_deal'),
  ('20260307_crm_advanced_features.sql','i','idx_deal_stage_history_org'),
  ('20260307_crm_advanced_features.sql','i','idx_lead_scores_contact'),
  ('20260307_crm_advanced_features.sql','i','idx_lead_scores_org'),
  ('20260307_crm_advanced_features.sql','i','idx_lead_scores_total'),
  ('20260307_crm_advanced_features.sql','i','idx_nps_responses_org'),
  ('20260307_crm_advanced_features.sql','i','idx_nps_responses_survey'),
  ('20260307_crm_advanced_features.sql','i','idx_sla_metrics_conversation'),
  ('20260307_crm_advanced_features.sql','i','idx_sla_metrics_org'),
  ('20260307_instagram_messaging.sql','t','public.instagram_accounts'),
  ('20260307_instagram_messaging.sql','t','public.instagram_contacts'),
  ('20260307_instagram_messaging.sql','t','public.instagram_conversations'),
  ('20260307_instagram_messaging.sql','t','public.instagram_messages'),
  ('20260307_instagram_messaging.sql','f','public.reset_instagram_daily_counters'),
  ('20260307_instagram_messaging.sql','f','public.update_instagram_updated_at'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_accounts_ig_user'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_accounts_org'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_accounts_status'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_contacts_crm'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_contacts_ig_user'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_contacts_org'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_conversations_account'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_conversations_assigned'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_conversations_contact'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_conversations_last_msg'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_conversations_org'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_conversations_status'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_messages_conversation'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_messages_message_id'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_messages_org'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_messages_status'),
  ('20260307_instagram_messaging.sql','i','idx_instagram_messages_timestamp'),
  ('20260307_lead_distribution_logs.sql','t','public.lead_distribution_logs'),
  ('20260307_lead_distribution_logs.sql','i','idx_distribution_logs_assigned_to'),
  ('20260307_lead_distribution_logs.sql','i','idx_distribution_logs_created_at'),
  ('20260307_lead_distribution_logs.sql','i','idx_distribution_logs_lead_id'),
  ('20260307_lead_distribution_logs.sql','i','idx_distribution_logs_rule_id'),
  ('20260330_shopify_graphql_cdp.sql','t','public.contact_events'),
  ('20260330_shopify_graphql_cdp.sql','t','public.shopify_webhook_log'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.browser'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.churn_risk'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.days_since_last_order'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.device_type'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.email_consent'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.email_consent_at'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.email_consent_source'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.first_order_at'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.last_active_at'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.lifecycle_stage'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.os'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.predicted_clv'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.rfm_frequency'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.rfm_monetary'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.rfm_recency'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.sms_consent'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.utm_campaign'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.utm_medium'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.utm_source'),
  ('20260330_shopify_graphql_cdp.sql','c','contacts.whatsapp_consent'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_checkouts.recovery_email_count'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_checkouts.recovery_email_sent_at'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_checkouts.status'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.api_version'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.embed_installed'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.initial_sync_completed'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.installed_at'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.pixel_installed'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.plan_name'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.scopes'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.settings'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.status'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.uninstalled_at'),
  ('20260330_shopify_graphql_cdp.sql','c','shopify_stores.webhook_secret'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_contact_events_anonymous'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_contact_events_contact'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_contact_events_idempotency'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_contact_events_org_occurred'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_contact_events_session'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_contact_events_shopify_resource'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_contact_events_type'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_webhook_log_id'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_webhook_log_store'),
  ('20260330_shopify_graphql_cdp.sql','i','idx_webhook_log_topic'),
  ('20260331_fix_missing_columns.sql','c','contacts.store_id'),
  ('20260331_fix_missing_columns.sql','c','shopify_customers.organization_id'),
  ('20260331_fix_missing_columns.sql','c','shopify_orders.organization_id'),
  ('20260331_fix_missing_columns.sql','c','shopify_products.organization_id'),
  ('20260401_cdp_tracking_enhancement.sql','t','public.visitor_sessions'),
  ('20260401_cdp_tracking_enhancement.sql','c','contact_events.fingerprint'),
  ('20260401_cdp_tracking_enhancement.sql','c','contact_events.visitor_id'),
  ('20260401_cdp_tracking_enhancement.sql','c','contacts.last_event_type'),
  ('20260401_cdp_tracking_enhancement.sql','c','contacts.total_events'),
  ('20260401_cdp_tracking_enhancement.sql','c','contacts.visitor_id'),
  ('20260401_cdp_tracking_enhancement.sql','i','idx_ce_fingerprint'),
  ('20260401_cdp_tracking_enhancement.sql','i','idx_ce_visitor'),
  ('20260401_cdp_tracking_enhancement.sql','i','idx_vs_contact'),
  ('20260401_cdp_tracking_enhancement.sql','i','idx_vs_fingerprint'),
  ('20260401_cdp_tracking_enhancement.sql','i','idx_vs_visitor'),
  ('20260401_flow_engine_tables.sql','t','public.automation_run_steps'),
  ('20260401_flow_engine_tables.sql','t','public.automation_runs'),
  ('20260401_flow_engine_tables.sql','t','public.event_logs'),
  ('20260401_flow_engine_tables.sql','i','idx_automation_runs_automation'),
  ('20260401_flow_engine_tables.sql','i','idx_automation_runs_pending'),
  ('20260401_flow_engine_tables.sql','i','idx_automation_runs_waiting'),
  ('20260401_flow_engine_tables.sql','i','idx_event_logs_org'),
  ('20260401_flow_engine_tables.sql','i','idx_event_logs_pending'),
  ('20260401_flow_engine_tables.sql','i','idx_run_steps_run'),
  ('20260401_store_isolation_tracking.sql','t','public.email_sends'),
  ('20260401_store_isolation_tracking.sql','c','customer_segments.store_id'),
  ('20260401_store_isolation_tracking.sql','c','email_campaigns.bounces'),
  ('20260401_store_isolation_tracking.sql','c','email_campaigns.clicks'),
  ('20260401_store_isolation_tracking.sql','c','email_campaigns.opens'),
  ('20260401_store_isolation_tracking.sql','c','email_campaigns.store_id'),
  ('20260401_store_isolation_tracking.sql','c','email_campaigns.total_failed'),
  ('20260401_store_isolation_tracking.sql','c','email_campaigns.total_recipients'),
  ('20260401_store_isolation_tracking.sql','c','email_campaigns.total_sent'),
  ('20260401_store_isolation_tracking.sql','c','email_campaigns.unsubscribes'),
  ('20260401_store_isolation_tracking.sql','c','email_templates.store_id'),
  ('20260401_store_isolation_tracking.sql','c','shopify_stores.total_customers'),
  ('20260401_store_isolation_tracking.sql','c','shopify_stores.total_orders'),
  ('20260401_store_isolation_tracking.sql','c','shopify_stores.total_products'),
  ('20260401_store_isolation_tracking.sql','c','shopify_stores.total_revenue'),
  ('20260401_store_isolation_tracking.sql','i','idx_customer_segments_store'),
  ('20260401_store_isolation_tracking.sql','i','idx_email_campaigns_store'),
  ('20260401_store_isolation_tracking.sql','i','idx_email_sends_campaign'),
  ('20260401_store_isolation_tracking.sql','i','idx_email_sends_contact'),
  ('20260401_store_isolation_tracking.sql','i','idx_email_sends_status'),
  ('20260401_store_isolation_tracking.sql','i','idx_email_templates_store'),
  ('20260402_popup_builder.sql','c','crm_forms.ab_parent_id'),
  ('20260402_popup_builder.sql','c','crm_forms.ab_variant'),
  ('20260402_popup_builder.sql','c','crm_forms.audience'),
  ('20260402_popup_builder.sql','c','crm_forms.behavior'),
  ('20260402_popup_builder.sql','c','crm_forms.conversion_rate'),
  ('20260402_popup_builder.sql','c','crm_forms.design_json'),
  ('20260402_popup_builder.sql','c','crm_forms.form_type'),
  ('20260402_popup_builder.sql','c','crm_forms.impressions_count'),
  ('20260402_popup_builder.sql','c','crm_forms.is_ab_test'),
  ('20260402_popup_builder.sql','c','crm_forms.list_id'),
  ('20260402_popup_builder.sql','c','crm_forms.store_id'),
  ('20260402_popup_builder.sql','c','crm_forms.tags'),
  ('20260402_popup_builder.sql','i','idx_crm_forms_store'),
  ('20260402_popup_builder.sql','i','idx_crm_forms_type'),
  ('20260406_flow_builder_complete_schema.sql','t','public.email_templates'),
  ('20260406_flow_builder_complete_schema.sql','t','public.list_contacts'),
  ('20260406_flow_builder_complete_schema.sql','t','public.lists'),
  ('20260406_flow_builder_complete_schema.sql','t','public.shopify_checkouts'),
  ('20260406_flow_builder_complete_schema.sql','t','public.shopify_orders'),
  ('20260406_flow_builder_complete_schema.sql','t','public.shopify_webhook_events'),
  ('20260406_flow_builder_complete_schema.sql','c','automation_run_steps.result'),
  ('20260406_flow_builder_complete_schema.sql','c','automation_run_steps.resume_at'),
  ('20260406_flow_builder_complete_schema.sql','c','automation_runs.last_error'),
  ('20260406_flow_builder_complete_schema.sql','c','automation_runs.metadata'),
  ('20260406_flow_builder_complete_schema.sql','c','automations.audience_filters'),
  ('20260406_flow_builder_complete_schema.sql','c','automations.exit_conditions'),
  ('20260406_flow_builder_complete_schema.sql','c','automations.frequency_config'),
  ('20260406_flow_builder_complete_schema.sql','c','automations.trigger_filters'),
  ('20260406_flow_builder_complete_schema.sql','c','email_sends.automation_id'),
  ('20260406_flow_builder_complete_schema.sql','c','email_sends.email_template_id'),
  ('20260406_flow_builder_complete_schema.sql','c','email_sends.resend_id'),
  ('20260406_flow_builder_complete_schema.sql','c','event_logs.error_message'),
  ('20260406_flow_builder_complete_schema.sql','c','event_logs.processed'),
  ('20260406_flow_builder_complete_schema.sql','c','event_logs.source'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_email_templates_org'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_email_templates_store'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_event_logs_unprocessed'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_list_contacts_contact'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_list_contacts_list'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_run_steps_node'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_run_steps_status'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_shopify_checkouts_contact'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_shopify_checkouts_store'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_shopify_orders_contact'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_shopify_orders_org'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_shopify_orders_shopify_id'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_shopify_orders_store'),
  ('20260406_flow_builder_complete_schema.sql','i','idx_shopify_webhook_events_event'),
  ('20260408_contacts_profile_fields.sql','c','contacts.address'),
  ('20260408_contacts_profile_fields.sql','c','contacts.birthday'),
  ('20260408_contacts_profile_fields.sql','c','contacts.city'),
  ('20260408_contacts_profile_fields.sql','c','contacts.country'),
  ('20260408_contacts_profile_fields.sql','c','contacts.custom_fields'),
  ('20260408_contacts_profile_fields.sql','c','contacts.gender'),
  ('20260408_contacts_profile_fields.sql','c','contacts.state'),
  ('20260408_contacts_profile_fields.sql','c','contacts.zip'),
  ('20260408_contacts_profile_fields.sql','i','idx_contacts_birthday'),
  ('20260408_contacts_profile_fields.sql','i','idx_contacts_city'),
  ('20260408_contacts_profile_fields.sql','i','idx_contacts_country'),
  ('20260408_contacts_profile_fields.sql','i','idx_contacts_state'),
  ('20260408_contacts_utm_data.sql','c','contacts.utm_data'),
  ('20260408_contacts_utm_data.sql','i','idx_contacts_utm_campaign'),
  ('20260408_contacts_utm_data.sql','i','idx_contacts_utm_source'),
  ('20260414_consolidated_pending.sql','t','public.saved_blocks'),
  ('20260414_consolidated_pending.sql','c','contacts.address'),
  ('20260414_consolidated_pending.sql','c','contacts.birthday'),
  ('20260414_consolidated_pending.sql','c','contacts.city'),
  ('20260414_consolidated_pending.sql','c','contacts.country'),
  ('20260414_consolidated_pending.sql','c','contacts.custom_fields'),
  ('20260414_consolidated_pending.sql','c','contacts.gender'),
  ('20260414_consolidated_pending.sql','c','contacts.state'),
  ('20260414_consolidated_pending.sql','c','contacts.utm_data'),
  ('20260414_consolidated_pending.sql','c','contacts.zip'),
  ('20260414_consolidated_pending.sql','i','idx_contacts_birthday'),
  ('20260414_consolidated_pending.sql','i','idx_contacts_city'),
  ('20260414_consolidated_pending.sql','i','idx_contacts_country'),
  ('20260414_consolidated_pending.sql','i','idx_contacts_state'),
  ('20260414_consolidated_pending.sql','i','idx_contacts_utm_campaign'),
  ('20260414_consolidated_pending.sql','i','idx_contacts_utm_source'),
  ('20260414_consolidated_pending.sql','i','idx_saved_blocks_category'),
  ('20260414_consolidated_pending.sql','i','idx_saved_blocks_org'),
  ('20260415_automation_workers_lock.sql','f','public.claim_automation_run'),
  ('20260415_automation_workers_lock.sql','f','public.heartbeat_automation_run'),
  ('20260415_automation_workers_lock.sql','f','public.reclaim_stale_automation_runs'),
  ('20260415_automation_workers_lock.sql','f','public.release_automation_run'),
  ('20260415_automation_workers_lock.sql','c','automation_pending_steps.lock_token'),
  ('20260415_automation_workers_lock.sql','c','automation_runs.lock_token'),
  ('20260415_automation_workers_lock.sql','i','automation_pending_steps_locked_idx'),
  ('20260415_automation_workers_lock.sql','i','automation_runs_locked_idx'),
  ('20260415_email_features.sql','t','public.saved_block_versions'),
  ('20260415_email_features.sql','f','public.bump_saved_block_version'),
  ('20260415_email_features.sql','c','email_campaigns.ab_test_enabled'),
  ('20260415_email_features.sql','c','email_sends.ab_variant'),
  ('20260415_email_features.sql','i','email_campaigns_scheduled_idx'),
  ('20260415_email_features.sql','i','saved_block_versions_org_idx'),
  ('20260415_email_features.sql','i','saved_block_versions_unique'),
  ('20260415_email_production_schema.sql','t','public.email_clicks'),
  ('20260415_email_production_schema.sql','t','public.email_domains'),
  ('20260415_email_production_schema.sql','f','public.attribute_email_conversion'),
  ('20260415_email_production_schema.sql','f','public.increment_campaign_bounces'),
  ('20260415_email_production_schema.sql','f','public.increment_campaign_clicks'),
  ('20260415_email_production_schema.sql','f','public.increment_campaign_opens'),
  ('20260415_email_production_schema.sql','f','public.increment_campaign_stats'),
  ('20260415_email_production_schema.sql','c','email_campaigns.completed_at'),
  ('20260415_email_production_schema.sql','c','email_campaigns.conversions'),
  ('20260415_email_production_schema.sql','c','email_campaigns.revenue'),
  ('20260415_email_production_schema.sql','c','email_campaigns.scheduled_at'),
  ('20260415_email_production_schema.sql','c','email_sends.automation_run_id'),
  ('20260415_email_production_schema.sql','c','email_sends.complained_at'),
  ('20260415_email_production_schema.sql','c','email_sends.conversion_value'),
  ('20260415_email_production_schema.sql','c','email_sends.converted_at'),
  ('20260415_email_production_schema.sql','c','email_sends.delivered_at'),
  ('20260415_email_production_schema.sql','c','email_sends.email_template_id'),
  ('20260415_email_production_schema.sql','c','email_sends.flow_id'),
  ('20260415_email_production_schema.sql','c','email_sends.order_id'),
  ('20260415_email_production_schema.sql','c','email_sends.unsubscribed_at'),
  ('20260415_email_production_schema.sql','i','idx_email_clicks_at'),
  ('20260415_email_production_schema.sql','i','idx_email_clicks_send'),
  ('20260415_email_production_schema.sql','i','idx_email_domains_org'),
  ('20260415_email_production_schema.sql','i','idx_email_sends_contact_sent'),
  ('20260415_email_production_schema.sql','i','idx_email_sends_org_created'),
  ('20260415_email_production_schema.sql','i','idx_email_sends_resend'),
  ('20260415_event_unification_and_indexes.sql','f','public.increment_campaign_clicks'),
  ('20260415_event_unification_and_indexes.sql','f','public.increment_campaign_opens'),
  ('20260415_event_unification_and_indexes.sql','f','public.increment_contact_events'),
  ('20260415_event_unification_and_indexes.sql','f','public.increment_contact_revenue'),
  ('20260415_event_unification_and_indexes.sql','c','automation_runs.result'),
  ('20260415_event_unification_and_indexes.sql','c','contact_events.store_id'),
  ('20260415_event_unification_and_indexes.sql','c','segments.member_count'),
  ('20260415_event_unification_and_indexes.sql','i','automation_runs_automation_status_idx'),
  ('20260415_event_unification_and_indexes.sql','i','automation_runs_status_created_idx'),
  ('20260415_event_unification_and_indexes.sql','i','contact_events_idempotency_key_uniq'),
  ('20260415_event_unification_and_indexes.sql','i','contact_events_org_contact_time_idx'),
  ('20260415_event_unification_and_indexes.sql','i','contact_events_org_type_time_idx'),
  ('20260415_event_unification_and_indexes.sql','i','contact_events_session_idx'),
  ('20260415_event_unification_and_indexes.sql','i','contact_events_store_time_idx'),
  ('20260415_event_unification_and_indexes.sql','i','contact_events_visitor_idx'),
  ('20260415_event_unification_and_indexes.sql','i','contacts_org_email_lower_idx'),
  ('20260415_event_unification_and_indexes.sql','i','contacts_org_phone_idx'),
  ('20260415_event_unification_and_indexes.sql','i','contacts_org_shopify_cust_idx'),
  ('20260415_event_unification_and_indexes.sql','i','email_sends_campaign_idx'),
  ('20260415_event_unification_and_indexes.sql','i','email_sends_contact_idx'),
  ('20260415_event_unification_and_indexes.sql','i','email_sends_status_created_idx'),
  ('20260415_event_unification_and_indexes.sql','i','segments_org_type_idx'),
  ('20260415_event_unification_and_indexes.sql','i','shopify_orders_org_created_idx'),
  ('20260415_event_unification_and_indexes.sql','i','shopify_orders_store_created_idx'),
  ('20260415_event_unification_and_indexes.sql','i','shopify_orders_store_customer_idx'),
  ('20260415_event_unification_and_indexes.sql','i','shopify_products_store_idx'),
  ('20260415_lgpd_lists_stripe.sql','t','public.billing_invoices'),
  ('20260415_lgpd_lists_stripe.sql','t','public.billing_subscriptions'),
  ('20260415_lgpd_lists_stripe.sql','t','public.lgpd_consents'),
  ('20260415_lgpd_lists_stripe.sql','t','public.lgpd_data_requests'),
  ('20260415_lgpd_lists_stripe.sql','t','public.lgpd_retention_policies'),
  ('20260415_lgpd_lists_stripe.sql','t','public.list_contacts'),
  ('20260415_lgpd_lists_stripe.sql','t','public.lists'),
  ('20260415_lgpd_lists_stripe.sql','f','public.update_list_member_count'),
  ('20260415_lgpd_lists_stripe.sql','i','billing_invoices_org_idx'),
  ('20260415_lgpd_lists_stripe.sql','i','billing_subscriptions_org_idx'),
  ('20260415_lgpd_lists_stripe.sql','i','lgpd_consents_org_contact_idx'),
  ('20260415_lgpd_lists_stripe.sql','i','lgpd_consents_visitor_idx'),
  ('20260415_lgpd_lists_stripe.sql','i','lgpd_data_requests_email_idx'),
  ('20260415_lgpd_lists_stripe.sql','i','lgpd_data_requests_org_status_idx'),
  ('20260415_lgpd_lists_stripe.sql','i','list_contacts_contact_idx'),
  ('20260415_lgpd_lists_stripe.sql','i','list_contacts_list_idx'),
  ('20260415_lgpd_lists_stripe.sql','i','list_contacts_unique'),
  ('20260415_lgpd_lists_stripe.sql','i','lists_org_idx'),
  ('20260415_product_interests_payment_links.sql','t','public.whatsapp_payment_links'),
  ('20260415_product_interests_payment_links.sql','t','public.whatsapp_product_interests'),
  ('20260415_product_interests_payment_links.sql','i','whatsapp_payment_links_contact_idx'),
  ('20260415_product_interests_payment_links.sql','i','whatsapp_payment_links_org_status_idx'),
  ('20260415_product_interests_payment_links.sql','i','whatsapp_product_interests_org_notified_idx'),
  ('20260415_product_interests_payment_links.sql','i','whatsapp_product_interests_product_idx'),
  ('20260415_product_interests_payment_links.sql','i','whatsapp_product_interests_unique'),
  ('20260415_segment_snapshots.sql','t','public.segment_memberships_snapshot'),
  ('20260415_segment_snapshots.sql','i','segment_snapshot_org_idx'),
  ('20260416_ai_costs_attribution.sql','t','public.ai_usage_logs'),
  ('20260416_ai_costs_attribution.sql','t','public.attribution_touchpoints'),
  ('20260416_ai_costs_attribution.sql','i','ai_usage_logs_org_created_idx'),
  ('20260416_ai_costs_attribution.sql','i','ai_usage_logs_org_feature_idx'),
  ('20260416_ai_costs_attribution.sql','i','ai_usage_logs_org_model_idx'),
  ('20260416_ai_costs_attribution.sql','i','attribution_touchpoints_contact_idx'),
  ('20260416_ai_costs_attribution.sql','i','attribution_touchpoints_org_utm_idx'),
  ('20260416_ai_costs_attribution.sql','i','attribution_touchpoints_visitor_idx'),
  ('20260416_consolidated_cleanup.sql','t','public.ai_knowledge_chunks'),
  ('20260416_consolidated_cleanup.sql','t','public.ai_knowledge_sources'),
  ('20260416_consolidated_cleanup.sql','t','public.ai_usage_logs'),
  ('20260416_consolidated_cleanup.sql','t','public.attribution_touchpoints'),
  ('20260416_consolidated_cleanup.sql','t','public.contact_rfm_scores'),
  ('20260416_consolidated_cleanup.sql','t','public.contact_tags'),
  ('20260416_consolidated_cleanup.sql','t','public.deal_activities'),
  ('20260416_consolidated_cleanup.sql','t','public.email_clicks'),
  ('20260416_consolidated_cleanup.sql','t','public.whatsapp_tags'),
  ('20260416_consolidated_cleanup.sql','t','public.whatsapp_transfers'),
  ('20260416_consolidated_cleanup.sql','c','email_campaigns.attributed_revenue'),
  ('20260416_consolidated_cleanup.sql','i','ai_knowledge_chunks_agent_idx'),
  ('20260416_consolidated_cleanup.sql','i','ai_knowledge_chunks_source_idx'),
  ('20260416_consolidated_cleanup.sql','i','ai_knowledge_sources_agent_idx'),
  ('20260416_consolidated_cleanup.sql','i','ai_knowledge_sources_org_idx'),
  ('20260416_consolidated_cleanup.sql','i','ai_usage_logs_org_created_idx'),
  ('20260416_consolidated_cleanup.sql','i','ai_usage_logs_org_feature_idx'),
  ('20260416_consolidated_cleanup.sql','i','ai_usage_logs_org_model_idx'),
  ('20260416_consolidated_cleanup.sql','i','attribution_touchpoints_contact_idx'),
  ('20260416_consolidated_cleanup.sql','i','attribution_touchpoints_org_utm_idx'),
  ('20260416_consolidated_cleanup.sql','i','attribution_touchpoints_visitor_idx'),
  ('20260416_consolidated_cleanup.sql','i','contact_rfm_scores_org_idx'),
  ('20260416_consolidated_cleanup.sql','i','contact_tags_org_tag_idx'),
  ('20260416_consolidated_cleanup.sql','i','contact_tags_unique'),
  ('20260416_consolidated_cleanup.sql','i','deal_activities_contact_idx'),
  ('20260416_consolidated_cleanup.sql','i','deal_activities_deal_idx'),
  ('20260416_consolidated_cleanup.sql','i','deal_activities_org_idx'),
  ('20260416_consolidated_cleanup.sql','i','email_clicks_send_idx'),
  ('20260416_consolidated_cleanup.sql','i','whatsapp_tags_org_name'),
  ('20260416_consolidated_cleanup.sql','i','whatsapp_transfers_conv_idx'),
  ('20260416_deal_activities_ai_knowledge.sql','t','public.ai_knowledge_chunks'),
  ('20260416_deal_activities_ai_knowledge.sql','t','public.ai_knowledge_sources'),
  ('20260416_deal_activities_ai_knowledge.sql','t','public.deal_activities'),
  ('20260416_deal_activities_ai_knowledge.sql','i','ai_knowledge_chunks_agent_idx'),
  ('20260416_deal_activities_ai_knowledge.sql','i','ai_knowledge_chunks_source_idx'),
  ('20260416_deal_activities_ai_knowledge.sql','i','ai_knowledge_sources_agent_idx'),
  ('20260416_deal_activities_ai_knowledge.sql','i','ai_knowledge_sources_org_idx'),
  ('20260416_deal_activities_ai_knowledge.sql','i','deal_activities_contact_idx'),
  ('20260416_deal_activities_ai_knowledge.sql','i','deal_activities_deal_idx'),
  ('20260416_deal_activities_ai_knowledge.sql','i','deal_activities_org_idx'),
  ('20260416_deliverability_smart_sending.sql','c','contacts.timezone'),
  ('20260416_deliverability_smart_sending.sql','c','email_campaigns.smart_sending_enabled'),
  ('20260416_deliverability_smart_sending.sql','c','email_domains.warmup_enabled'),
  ('20260416_deliverability_smart_sending.sql','c','email_sends.isp_domain'),
  ('20260416_deliverability_smart_sending.sql','i','contacts_engagement_idx'),
  ('20260416_deliverability_smart_sending.sql','i','contacts_timezone_idx'),
  ('20260416_deliverability_smart_sending.sql','i','email_sends_contact_recent_idx'),
  ('20260416_deliverability_smart_sending.sql','i','email_sends_isp_idx'),
  ('20260416_missing_tables.sql','t','public.contact_rfm_scores'),
  ('20260416_missing_tables.sql','t','public.contact_tags'),
  ('20260416_missing_tables.sql','t','public.email_clicks'),
  ('20260416_missing_tables.sql','t','public.whatsapp_tags'),
  ('20260416_missing_tables.sql','t','public.whatsapp_transfers'),
  ('20260416_missing_tables.sql','c','email_campaigns.attributed_revenue'),
  ('20260416_missing_tables.sql','i','contact_rfm_scores_org_idx'),
  ('20260416_missing_tables.sql','i','contact_tags_org_tag_idx'),
  ('20260416_missing_tables.sql','i','contact_tags_unique'),
  ('20260416_missing_tables.sql','i','email_clicks_send_idx'),
  ('20260416_missing_tables.sql','i','whatsapp_tags_org_name'),
  ('20260416_missing_tables.sql','i','whatsapp_transfers_conv_idx'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.abandoned_at'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.abandoned_checkout_url'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.converted_at'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.converted_order_id'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.customer_shopify_id'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.phone'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.recovered_at'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.recovery_url'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.shopify_created_at'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.shopify_updated_at'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.status'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.subtotal_price'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.total_discounts'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.total_price'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_checkouts.total_tax'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_webhook_events.organization_id'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_webhook_events.payload'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_webhook_events.received_at'),
  ('20260417_shopify_checkouts_columns.sql','c','shopify_webhook_events.shopify_event_id'),
  ('20260417_shopify_checkouts_columns.sql','i','idx_shopify_checkouts_org_status'),
  ('20260417_shopify_checkouts_columns.sql','i','idx_shopify_checkouts_store_status'),
  ('20260419_browse_abandoned_emissions.sql','t','public.browse_abandoned_emissions'),
  ('20260419_browse_abandoned_emissions.sql','i','idx_browse_aband_org_emitted'),
  ('20260419_browse_abandoned_rpc.sql','f','public.detect_browse_abandoned'),
  ('20260419_webhook_deliveries.sql','t','public.webhook_deliveries'),
  ('20260419_webhook_deliveries.sql','i','idx_webhook_deliv_org'),
  ('20260419_webhook_deliveries.sql','i','idx_webhook_deliv_status'),
  ('20260419_webhook_deliveries.sql','i','idx_webhook_deliv_stuck'),
  ('20260419_webhook_deliveries.sql','i','idx_webhook_deliv_sub'),
  ('20260419_webhook_pii_consent.sql','t','public.audit_logs'),
  ('20260419_webhook_pii_consent.sql','i','idx_audit_logs_org_action'),
  ('20260419_webhook_rpcs.sql','f','public.claim_webhook_delivery'),
  ('20260419_webhook_rpcs.sql','f','public.dispatch_insert_deliveries'),
  ('20260419_webhook_subscriptions.sql','t','public.webhook_subscriptions'),
  ('20260419_webhook_subscriptions.sql','f','public.update_webhook_subscriptions_updated_at'),
  ('20260419_webhook_subscriptions.sql','i','idx_webhook_subs_lookup'),
  ('20260419_webhook_subscriptions.sql','i','idx_webhook_subs_org'),
  ('20260420_audit_logs_defensive.sql','t','public.audit_logs'),
  ('20260420_audit_logs_defensive.sql','c','audit_logs.action'),
  ('20260420_audit_logs_defensive.sql','c','audit_logs.created_at'),
  ('20260420_audit_logs_defensive.sql','c','audit_logs.metadata'),
  ('20260420_audit_logs_defensive.sql','c','audit_logs.organization_id'),
  ('20260420_audit_logs_defensive.sql','c','audit_logs.user_id'),
  ('20260420_audit_logs_defensive.sql','i','idx_audit_logs_org_action'),
  ('20260420_count_events_rpc.sql','f','public.count_events_by_type'),
  ('20260420_count_events_rpc.sql','i','idx_contact_events_org_occurred'),
  ('20260420_saved_blocks_updated_at.sql','f','public.touch_saved_blocks_updated_at'),
  ('20260420_saved_blocks_updated_at.sql','c','saved_blocks.updated_at'),
  ('20260420_shopify_orders_payment_gateway.sql','c','shopify_orders.payment_gateway_names'),
  ('20260420_shopify_orders_payment_gateway.sql','i','idx_shopify_orders_financial_status'),
  ('20260420_shopify_orders_payment_gateway.sql','i','idx_shopify_orders_payment_gateway'),
  ('20260506_identity_and_recommendations.sql','t','public.product_recommendations'),
  ('20260506_identity_and_recommendations.sql','t','public.visitor_id_aliases'),
  ('20260506_identity_and_recommendations.sql','t','public.visitor_identities'),
  ('20260506_identity_and_recommendations.sql','f','public.worder_hash_email'),
  ('20260506_identity_and_recommendations.sql','f','public.worder_hash_phone'),
  ('20260506_identity_and_recommendations.sql','i','idx_product_recs_lookup'),
  ('20260506_identity_and_recommendations.sql','i','idx_product_recs_store'),
  ('20260506_identity_and_recommendations.sql','i','idx_visitor_id_aliases_alias'),
  ('20260506_identity_and_recommendations.sql','i','idx_visitor_id_aliases_identity'),
  ('20260506_identity_and_recommendations.sql','i','idx_visitor_identities_contact'),
  ('20260506_identity_and_recommendations.sql','i','idx_visitor_identities_email'),
  ('20260506_identity_and_recommendations.sql','i','idx_visitor_identities_fingerprint'),
  ('20260506_identity_and_recommendations.sql','i','idx_visitor_identities_last_seen'),
  ('20260506_identity_and_recommendations.sql','i','idx_visitor_identities_shopify'),
  ('20260506_identity_and_recommendations.sql','i','idx_visitor_identities_worder_id'),
  ('20260506_shopify_domain_aliases.sql','c','shopify_stores.shop_domain_aliases'),
  ('20260506_shopify_domain_aliases.sql','i','idx_shopify_stores_domain_aliases'),
  ('20260506_shopify_shop_id.sql','c','shopify_stores.shopify_shop_id'),
  ('20260506_shopify_shop_id.sql','i','idx_shopify_stores_shop_id'),
  ('20260506_shopify_webhook_audit.sql','t','public.shopify_webhook_audit'),
  ('20260506_shopify_webhook_audit.sql','i','idx_shopify_webhook_audit_received'),
  ('20260506_shopify_webhook_audit.sql','i','idx_shopify_webhook_audit_shop'),
  ('20260507_custom_variables.sql','t','public.custom_variables'),
  ('20260507_custom_variables.sql','i','idx_custom_variables_org'),
  ('20260507_custom_variables.sql','i','idx_custom_variables_store'),
  ('20260508_automation_runs_full_columns.sql','c','automation_runs.lock_token'),
  ('20260508_automation_runs_full_columns.sql','c','automation_runs.organization_id'),
  ('20260508_automation_runs_full_columns.sql','c','automation_runs.result'),
  ('20260508_automation_runs_full_columns.sql','c','automation_runs.waiting_until'),
  ('20260508_automation_runs_full_columns.sql','c','contact_activities.organization_id'),
  ('20260508_automation_runs_full_columns.sql','i','idx_automation_runs_automation'),
  ('20260508_automation_runs_full_columns.sql','i','idx_automation_runs_idempotency'),
  ('20260508_automation_runs_full_columns.sql','i','idx_automation_runs_org'),
  ('20260508_automation_runs_full_columns.sql','i','idx_automation_runs_pending'),
  ('20260508_automation_runs_full_columns.sql','i','idx_automation_runs_waiting'),
  ('20260508_shopify_products_description.sql','c','shopify_products.description'),
  ('20260509_klaviyo_omnisend_parity.sql','t','public.price_drop_subscriptions'),
  ('20260509_klaviyo_omnisend_parity.sql','c','automations.audience_filters'),
  ('20260509_klaviyo_omnisend_parity.sql','c','automations.exit_conditions'),
  ('20260509_klaviyo_omnisend_parity.sql','c','automations.frequency_config'),
  ('20260509_klaviyo_omnisend_parity.sql','c','automations.trigger_filters'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.email_provider'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.email_provider_config'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.max_email_per_contact_per_day'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.max_sends_per_contact_per_day'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.max_sms_per_contact_per_day'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.max_whatsapp_per_contact_per_day'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.quiet_hours_enabled'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.quiet_hours_end'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.quiet_hours_start'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.quiet_hours_timezone'),
  ('20260509_klaviyo_omnisend_parity.sql','c','organizations.skip_contacts_in_active_flows'),
  ('20260509_klaviyo_omnisend_parity.sql','i','idx_price_drop_subs_product'),
  ('20260513_attribute_email_conversion_idempotent.sql','f','public.attribute_email_conversion'),
  ('20260513_contact_events_conversion_guard_idx.sql','i','contact_events_contact_type_time_idx'),
  ('20260513_email_domains_per_store.sql','c','email_domains.is_system'),
  ('20260513_email_domains_per_store.sql','c','email_domains.store_id'),
  ('20260513_email_domains_per_store.sql','i','email_domains_is_system_idx'),
  ('20260513_email_domains_per_store.sql','i','email_domains_store_idx'),
  ('20260513_form_events.sql','t','public.form_events'),
  ('20260513_form_events.sql','f','public.increment_form_counter'),
  ('20260513_form_events.sql','c','forms.dismissals_count'),
  ('20260513_form_events.sql','i','form_events_event_type_idx'),
  ('20260513_form_events.sql','i','form_events_org_form_time_idx'),
  ('20260513_multi_channel_attribution.sql','t','public.sms_campaigns'),
  ('20260513_multi_channel_attribution.sql','t','public.sms_sends'),
  ('20260513_multi_channel_attribution.sql','t','public.whatsapp_sends'),
  ('20260513_multi_channel_attribution.sql','f','public.attribute_email_conversion'),
  ('20260513_multi_channel_attribution.sql','f','public.attribute_sms_conversion'),
  ('20260513_multi_channel_attribution.sql','f','public.attribute_whatsapp_conversion'),
  ('20260513_multi_channel_attribution.sql','f','public.backfill_attribution_for_org'),
  ('20260513_multi_channel_attribution.sql','f','public.revoke_email_conversion'),
  ('20260513_multi_channel_attribution.sql','f','public.revoke_sms_conversion'),
  ('20260513_multi_channel_attribution.sql','f','public.revoke_whatsapp_conversion'),
  ('20260513_multi_channel_attribution.sql','f','public.trg_touch_updated_at'),
  ('20260513_multi_channel_attribution.sql','c','email_campaigns.revenue'),
  ('20260513_multi_channel_attribution.sql','c','email_sends.mpp_opened_at'),
  ('20260513_multi_channel_attribution.sql','c','whatsapp_campaigns.revenue'),
  ('20260513_multi_channel_attribution.sql','i','email_sends_mpp_opened_idx'),
  ('20260513_multi_channel_attribution.sql','i','sms_sends_attribution_idx'),
  ('20260513_multi_channel_attribution.sql','i','sms_sends_automation_run_idx'),
  ('20260513_multi_channel_attribution.sql','i','sms_sends_campaign_idx'),
  ('20260513_multi_channel_attribution.sql','i','sms_sends_external_msg_idx'),
  ('20260513_multi_channel_attribution.sql','i','sms_sends_flow_idx'),
  ('20260513_multi_channel_attribution.sql','i','sms_sends_order_idempotency_idx'),
  ('20260513_multi_channel_attribution.sql','i','sms_sends_org_contact_idx'),
  ('20260513_multi_channel_attribution.sql','i','whatsapp_sends_attribution_idx'),
  ('20260513_multi_channel_attribution.sql','i','whatsapp_sends_automation_run_idx'),
  ('20260513_multi_channel_attribution.sql','i','whatsapp_sends_campaign_idx'),
  ('20260513_multi_channel_attribution.sql','i','whatsapp_sends_external_msg_idx'),
  ('20260513_multi_channel_attribution.sql','i','whatsapp_sends_flow_idx'),
  ('20260513_multi_channel_attribution.sql','i','whatsapp_sends_order_idempotency_idx'),
  ('20260513_multi_channel_attribution.sql','i','whatsapp_sends_org_contact_idx'),
  ('20260513_shopify_import_jobs_resume_idx.sql','i','shopify_import_jobs_resume_idx'),
  ('20260513_shopify_stores_embed_installed_at.sql','c','shopify_stores.embed_installed_at'),
  ('20260515_contacts_unique_org_email.sql','i','contacts_org_email_unique'),
  ('20260515_refresh_contact_order_metrics.sql','f','public.refresh_contact_order_metrics'),
  ('20260516_contacts_store_id_trigger.sql','f','public.contacts_fill_store_id'),
  ('20260516_shopify_orders_payment_gateway_names.sql','c','shopify_orders.payment_gateway_names'),
  ('20260516_shopify_orders_total_refunded.sql','c','shopify_orders.total_refunded'),
  ('20260516_shopify_schema_alignment.sql','c','shopify_customers.currency'),
  ('20260516_shopify_schema_alignment.sql','i','contacts_org_email_unique'),
  ('20260518_segments_v2_foundation.sql','t','public.contact_list_members'),
  ('20260518_segments_v2_foundation.sql','t','public.contact_lists'),
  ('20260518_segments_v2_foundation.sql','t','public.segment_member_cache'),
  ('20260518_segments_v2_foundation.sql','t','public.segment_reeval_queue'),
  ('20260518_segments_v2_foundation.sql','f','public.contact_list_members_sync_count'),
  ('20260518_segments_v2_foundation.sql','f','public.contact_lists_set_updated_at'),
  ('20260518_segments_v2_foundation.sql','c','customer_segments.rule_version'),
  ('20260518_segments_v2_foundation.sql','i','idx_clm_contact'),
  ('20260518_segments_v2_foundation.sql','i','idx_contact_lists_org'),
  ('20260518_segments_v2_foundation.sql','i','idx_contact_lists_store'),
  ('20260518_segments_v2_foundation.sql','i','idx_smc_contact'),
  ('20260518_segments_v2_foundation.sql','i','idx_srq_pending'),
  ('20260522_organizations_feature_flags.sql','c','organizations.feature_flags'),
  ('20260522_organizations_feature_flags.sql','c','whatsapp_business_accounts.connection_method'),
  ('20260522_organizations_feature_flags.sql','i','idx_organizations_feature_flags'),
  ('20260522_whatsapp_access_token_encrypted.sql','c','whatsapp_business_accounts.access_token_encrypted'),
  ('20260522_whatsapp_access_token_encrypted.sql','c','whatsapp_instances.access_token_encrypted'),
  ('20260522_whatsapp_webhook_events.sql','t','public.whatsapp_webhook_events'),
  ('20260522_whatsapp_webhook_events.sql','f','public.claim_whatsapp_webhook_event'),
  ('20260522_whatsapp_webhook_events.sql','f','public.pending_whatsapp_webhook_events_for_reprocess'),
  ('20260522_whatsapp_webhook_events.sql','i','idx_whatsapp_webhook_events_done_processed'),
  ('20260522_whatsapp_webhook_events.sql','i','idx_whatsapp_webhook_events_phone_number'),
  ('20260522_whatsapp_webhook_events.sql','i','idx_whatsapp_webhook_events_status_received'),
  ('20260606_whatsapp_optout_compliance.sql','c','whatsapp_opt_status.consent_evidence'),
  ('20260606_whatsapp_optout_compliance.sql','i','idx_whatsapp_opt_status_lookup'),
  ('20260607_whatsapp_accounts_phone_unique_per_org.sql','i','idx_wba_org_phone_number_id'),
  ('20260607_whatsapp_accounts_phone_unique_per_org.sql','i','idx_wba_waba_id_unique'),
  ('20260607_whatsapp_accounts_token_invalid_at.sql','c','whatsapp_business_accounts.token_invalid_at'),
  ('20260607_whatsapp_accounts_token_invalid_at.sql','c','whatsapp_business_accounts.token_invalid_code'),
  ('20260607_whatsapp_accounts_token_invalid_at.sql','c','whatsapp_business_accounts.token_invalid_message'),
  ('20260607_whatsapp_conversation_counters_rpc.sql','f','public.increment_account_inbound'),
  ('20260607_whatsapp_conversation_counters_rpc.sql','f','public.increment_conversation_inbound'),
  ('20260610_ai_agent_versions.sql','t','public.ai_agent_versions'),
  ('20260610_ai_agent_versions.sql','f','public.user_belongs_to_org'),
  ('20260610_ai_agent_versions.sql','i','idx_agent_versions_agent'),
  ('20260610_ai_agent_versions.sql','i','idx_agent_versions_one_production'),
  ('20260611_agent_trace_annotations.sql','t','public.agent_trace_annotations'),
  ('20260611_agent_trace_annotations.sql','f','public.user_belongs_to_org'),
  ('20260611_agent_trace_annotations.sql','i','idx_trace_annotations_agent'),
  ('20260612_ai_test_scenarios.sql','t','public.ai_scenario_runs'),
  ('20260612_ai_test_scenarios.sql','t','public.ai_test_scenarios'),
  ('20260612_ai_test_scenarios.sql','f','public.user_belongs_to_org'),
  ('20260612_ai_test_scenarios.sql','i','idx_scenario_runs_agent'),
  ('20260612_ai_test_scenarios.sql','i','idx_scenario_runs_scenario'),
  ('20260612_ai_test_scenarios.sql','i','idx_test_scenarios_agent'),
  ('20260613_agent_stats_rpcs.sql','f','public.increment_agent_conversations'),
  ('20260613_agent_stats_rpcs.sql','f','public.update_agent_stats'),
  ('20260613_ai_eval_tables.sql','t','public.ai_eval_cases'),
  ('20260613_ai_eval_tables.sql','t','public.ai_eval_criteria'),
  ('20260613_ai_eval_tables.sql','t','public.ai_eval_results'),
  ('20260613_ai_eval_tables.sql','f','public.user_belongs_to_org'),
  ('20260613_ai_eval_tables.sql','i','idx_eval_cases_agent'),
  ('20260613_ai_eval_tables.sql','i','idx_eval_criteria_agent'),
  ('20260613_ai_eval_tables.sql','i','idx_eval_results_agent'),
  ('20260614_ai_prompt_proposals.sql','t','public.ai_prompt_proposals'),
  ('20260614_ai_prompt_proposals.sql','f','public.user_belongs_to_org'),
  ('20260614_ai_prompt_proposals.sql','i','idx_prompt_proposals_agent'),
  ('20260615_whatsapp_campaign_pipeline.sql','f','public.apply_campaign_recipient_webhook'),
  ('20260615_whatsapp_campaign_pipeline.sql','f','public.claim_due_whatsapp_campaigns'),
  ('20260615_whatsapp_campaign_pipeline.sql','i','idx_campaigns_queued_reclaim'),
  ('20260615_whatsapp_campaign_pipeline.sql','i','idx_campaigns_scheduled'),
  ('20260615_whatsapp_campaign_pipeline.sql','i','idx_recipients_meta_msg_notnull'),
  ('20260615_whatsapp_campaign_pipeline.sql','i','idx_scheduled_messages_due'),
  ('20260616_ai_budgets.sql','t','public.ai_budgets'),
  ('20260616_ai_budgets.sql','f','public.ai_monthly_cost_usd'),
  ('20260616_ai_budgets.sql','c','ai_usage_logs.completion_tokens'),
  ('20260616_ai_budgets.sql','c','ai_usage_logs.cost_usd'),
  ('20260616_ai_budgets.sql','c','ai_usage_logs.duration_ms'),
  ('20260616_ai_budgets.sql','c','ai_usage_logs.error'),
  ('20260616_ai_budgets.sql','c','ai_usage_logs.feature'),
  ('20260616_ai_budgets.sql','c','ai_usage_logs.metadata'),
  ('20260616_ai_budgets.sql','c','ai_usage_logs.prompt_tokens'),
  ('20260616_ai_budgets.sql','i','ai_budgets_org_idx'),
  ('20260616_ai_budgets.sql','i','ai_usage_logs_org_created_idx'),
  ('20260619_whatsapp_ai_retry.sql','f','public.pending_whatsapp_ai_responses_for_reprocess'),
  ('20260619_whatsapp_ai_retry.sql','c','whatsapp_cloud_conversations.ai_retry_count'),
  ('20260619_whatsapp_ai_retry.sql','i','idx_wcc_ai_pending_debounce'),
  ('20260620_find_matching_automations_store_scope.sql','f','public.find_matching_automations'),
  ('20260720_fix_whatsapp_messages_trigger_columns.sql','c','whatsapp_conversations.last_message_type'),
  ('20260720_fix_whatsapp_messages_trigger_columns.sql','c','whatsapp_conversations.total_messages'),
  ('20260720_unified_inbox_unique_indexes.sql','i','whatsapp_conversations_instance_phone_unique'),
  ('20260720_unified_inbox_unique_indexes.sql','i','whatsapp_messages_wamid_unique'),
  ('20260727_ai_transfer_cooldown.sql','c','whatsapp_cloud_conversations.ai_transferred_at'),
  ('20260727_inbound_media_pipeline.sql','c','whatsapp_cloud_messages.delivered_at'),
  ('20260727_inbound_media_pipeline.sql','c','whatsapp_cloud_messages.media_url'),
  ('20260727_inbound_media_pipeline.sql','c','whatsapp_messages.media_url'),
  ('20260727_wcm_delivery_read_receipts.sql','c','whatsapp_cloud_messages.delivered_at'),
  ('20260727_wcm_delivery_read_receipts.sql','c','whatsapp_cloud_messages.media_url'),
  ('20260727_wcm_delivery_read_receipts.sql','c','whatsapp_messages.media_url'),
  ('20260730_notifications_action_columns.sql','c','notifications.action_url'),
  ('20260730_whatsapp_ai_run_steps.sql','t','public.whatsapp_ai_run_steps'),
  ('20260730_whatsapp_ai_run_steps.sql','i','idx_wars_conversation_created'),
  ('20260730_whatsapp_ai_run_steps.sql','i','idx_wars_run'),
  ('2026_06_22_email_template_versions.sql','t','public.email_template_versions'),
  ('2026_06_22_email_template_versions.sql','f','public.bump_email_template_version'),
  ('2026_06_22_email_template_versions.sql','i','email_template_versions_org_idx'),
  ('2026_06_22_email_template_versions.sql','i','email_template_versions_unique'),
  ('2026_06_22_text_based_email_templates.sql','c','email_templates.editor_type'),
  ('2026_06_22_text_based_email_templates.sql','i','email_templates_editor_type_idx'),
  ('2026_07_02_form_events_crm_forms.sql','t','public.form_events'),
  ('2026_07_02_form_events_crm_forms.sql','f','public.increment_crm_form_counter'),
  ('2026_07_02_form_events_crm_forms.sql','c','crm_forms.dismissals_count'),
  ('2026_07_02_form_events_crm_forms.sql','i','form_events_event_type_idx'),
  ('2026_07_02_form_events_crm_forms.sql','i','form_events_org_form_time_idx'),
  ('PARTE1_tabelas_ads.sql','t','public.google_ads_accounts'),
  ('PARTE1_tabelas_ads.sql','t','public.google_ads_ad_groups'),
  ('PARTE1_tabelas_ads.sql','t','public.google_ads_campaigns'),
  ('PARTE1_tabelas_ads.sql','t','public.google_ads_keywords'),
  ('PARTE1_tabelas_ads.sql','t','public.google_ads_metrics'),
  ('PARTE1_tabelas_ads.sql','t','public.google_ads_product_metrics'),
  ('PARTE1_tabelas_ads.sql','t','public.google_ads_products'),
  ('PARTE1_tabelas_ads.sql','t','public.google_ads_search_terms'),
  ('PARTE1_tabelas_ads.sql','t','public.meta_ads_accounts'),
  ('PARTE1_tabelas_ads.sql','t','public.meta_ads_ads'),
  ('PARTE1_tabelas_ads.sql','t','public.meta_ads_adsets'),
  ('PARTE1_tabelas_ads.sql','t','public.meta_ads_campaigns'),
  ('PARTE1_tabelas_ads.sql','t','public.meta_ads_metrics'),
  ('PARTE1_tabelas_ads.sql','t','public.tiktok_ads_accounts'),
  ('PARTE1_tabelas_ads.sql','t','public.tiktok_ads_adgroups'),
  ('PARTE1_tabelas_ads.sql','t','public.tiktok_ads_campaigns'),
  ('PARTE1_tabelas_ads.sql','t','public.tiktok_ads_metrics'),
  ('PARTE1_tabelas_ads.sql','i','idx_google_ads_metrics_campaign'),
  ('PARTE1_tabelas_ads.sql','i','idx_google_ads_metrics_org_date'),
  ('PARTE1_tabelas_ads.sql','i','idx_meta_ads_metrics_org_date'),
  ('PARTE1_tabelas_ads.sql','i','idx_tiktok_ads_metrics_org_date'),
  ('PARTE2_help_e_outras_tabelas.sql','t','public.abandoned_carts'),
  ('PARTE2_help_e_outras_tabelas.sql','t','public.credentials'),
  ('PARTE2_help_e_outras_tabelas.sql','t','public.faq_items'),
  ('PARTE2_help_e_outras_tabelas.sql','t','public.help_articles'),
  ('PARTE2_help_e_outras_tabelas.sql','t','public.help_categories'),
  ('PARTE2_help_e_outras_tabelas.sql','t','public.notifications'),
  ('PARTE2_help_e_outras_tabelas.sql','t','public.orders'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_abandoned_carts_contact'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_abandoned_carts_org'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_abandoned_carts_status'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_credentials_org_type'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_faq_items_category'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_help_articles_category'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_help_articles_status'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_notifications_org'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_notifications_user'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_orders_contact'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_orders_external'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_orders_org'),
  ('PARTE2_help_e_outras_tabelas.sql','i','idx_orders_status'),
  ('PARTE4_custos_e_taxas.sql','t','public.custom_fees'),
  ('PARTE4_custos_e_taxas.sql','t','public.exchange_rates'),
  ('PARTE4_custos_e_taxas.sql','t','public.organization_tax_settings'),
  ('PARTE4_custos_e_taxas.sql','t','public.product_costs'),
  ('PARTE4_custos_e_taxas.sql','t','public.shopify_products_cache'),
  ('PARTE4_custos_e_taxas.sql','i','idx_custom_fees_org'),
  ('PARTE4_custos_e_taxas.sql','i','idx_exchange_rates_date'),
  ('PARTE4_custos_e_taxas.sql','i','idx_product_costs_org'),
  ('PARTE4_custos_e_taxas.sql','i','idx_product_costs_product'),
  ('PARTE4_custos_e_taxas.sql','i','idx_product_costs_store'),
  ('PARTE4_custos_e_taxas.sql','i','idx_shopify_products_cache_org'),
  ('PARTE4_custos_e_taxas.sql','i','idx_shopify_products_cache_store'),
  ('add-shopify-import-columns.sql','c','shopify_stores.health_checked_at'),
  ('add-shopify-import-columns.sql','c','shopify_stores.is_configured'),
  ('add-shopify-import-columns.sql','c','shopify_stores.metrics'),
  ('add-shopify-import-columns.sql','c','shopify_stores.total_customers_imported'),
  ('add-shopify-import-columns.sql','i','idx_shopify_stores_connection_status'),
  ('add-shopify-import-columns.sql','i','idx_shopify_stores_org_active'),
  ('crm-automation-rules.sql','t','public.crm_automation_rules'),
  ('crm-automation-rules.sql','f','public.update_automation_rules_updated_at'),
  ('crm-automation-rules.sql','i','idx_automation_rules_active'),
  ('crm-automation-rules.sql','i','idx_automation_rules_org'),
  ('crm-automation-rules.sql','i','idx_automation_rules_pipeline'),
  ('crm-automation-rules.sql','i','idx_automation_rules_source'),
  ('flow-builder-execution-history.sql','t','public.automation_executions'),
  ('flow-builder-execution-history.sql','f','public.cleanup_old_executions'),
  ('flow-builder-execution-history.sql','f','public.get_executions_to_resume'),
  ('flow-builder-execution-history.sql','f','public.update_automation_execution_stats'),
  ('flow-builder-execution-history.sql','c','credentials.usage_count'),
  ('flow-builder-execution-history.sql','i','idx_automation_executions_automation'),
  ('flow-builder-execution-history.sql','i','idx_automation_executions_contact'),
  ('flow-builder-execution-history.sql','i','idx_automation_executions_org'),
  ('flow-builder-execution-history.sql','i','idx_automation_executions_started'),
  ('flow-builder-execution-history.sql','i','idx_automation_executions_status'),
  ('flow-builder-execution-history.sql','i','idx_automation_executions_waiting'),
  ('flow-builder-v2-corrigido.sql','t','public.automation_templates'),
  ('flow-builder-v2-corrigido.sql','t','public.automation_versions'),
  ('flow-builder-v2-corrigido.sql','t','public.credentials'),
  ('flow-builder-v2-corrigido.sql','t','public.flow_webhook_logs'),
  ('flow-builder-v2-corrigido.sql','t','public.flow_webhooks'),
  ('flow-builder-v2-corrigido.sql','t','public.scheduled_executions'),
  ('flow-builder-v2-corrigido.sql','f','public.increment_flow_webhook_count'),
  ('flow-builder-v2-corrigido.sql','f','public.increment_template_usage'),
  ('flow-builder-v2-corrigido.sql','f','public.update_automation_stats'),
  ('flow-builder-v2-corrigido.sql','c','automation_executions.final_context'),
  ('flow-builder-v2-corrigido.sql','c','automation_executions.resume_data'),
  ('flow-builder-v2-corrigido.sql','c','automation_executions.retry_count'),
  ('flow-builder-v2-corrigido.sql','c','automation_executions.retry_of'),
  ('flow-builder-v2-corrigido.sql','c','automation_executions.wait_till'),
  ('flow-builder-v2-corrigido.sql','c','automations.error_count'),
  ('flow-builder-v2-corrigido.sql','c','automations.last_success_at'),
  ('flow-builder-v2-corrigido.sql','c','automations.published_version'),
  ('flow-builder-v2-corrigido.sql','c','automations.static_data'),
  ('flow-builder-v2-corrigido.sql','c','automations.store_id'),
  ('flow-builder-v2-corrigido.sql','c','automations.success_count'),
  ('flow-builder-v2-corrigido.sql','c','automations.version'),
  ('flow-builder-v2-corrigido.sql','i','idx_automation_templates_category'),
  ('flow-builder-v2-corrigido.sql','i','idx_automation_templates_featured'),
  ('flow-builder-v2-corrigido.sql','i','idx_automation_versions_automation'),
  ('flow-builder-v2-corrigido.sql','i','idx_automations_status'),
  ('flow-builder-v2-corrigido.sql','i','idx_automations_store'),
  ('flow-builder-v2-corrigido.sql','i','idx_credentials_org'),
  ('flow-builder-v2-corrigido.sql','i','idx_credentials_type'),
  ('flow-builder-v2-corrigido.sql','i','idx_executions_waiting'),
  ('flow-builder-v2-corrigido.sql','i','idx_flow_webhook_logs_received'),
  ('flow-builder-v2-corrigido.sql','i','idx_flow_webhook_logs_webhook'),
  ('flow-builder-v2-corrigido.sql','i','idx_flow_webhooks_automation'),
  ('flow-builder-v2-corrigido.sql','i','idx_flow_webhooks_token'),
  ('flow-builder-v2-corrigido.sql','i','idx_scheduled_executions_automation'),
  ('flow-builder-v2-corrigido.sql','i','idx_scheduled_executions_next'),
  ('flow-builder-v3-complete.sql','t','public.automation_run_steps'),
  ('flow-builder-v3-complete.sql','t','public.automation_runs'),
  ('flow-builder-v3-complete.sql','t','public.credentials'),
  ('flow-builder-v3-complete.sql','f','public.update_automation_stats'),
  ('flow-builder-v3-complete.sql','c','automations.activated_at'),
  ('flow-builder-v3-complete.sql','c','automations.created_by'),
  ('flow-builder-v3-complete.sql','c','automations.edges'),
  ('flow-builder-v3-complete.sql','c','automations.failed_runs'),
  ('flow-builder-v3-complete.sql','c','automations.last_run_at'),
  ('flow-builder-v3-complete.sql','c','automations.nodes'),
  ('flow-builder-v3-complete.sql','c','automations.paused_at'),
  ('flow-builder-v3-complete.sql','c','automations.status'),
  ('flow-builder-v3-complete.sql','c','automations.successful_runs'),
  ('flow-builder-v3-complete.sql','c','automations.total_runs'),
  ('flow-builder-v3-complete.sql','c','automations.trigger_config'),
  ('flow-builder-v3-complete.sql','c','automations.trigger_type'),
  ('flow-builder-v3-complete.sql','i','idx_automation_run_steps_run'),
  ('flow-builder-v3-complete.sql','i','idx_automation_runs_automation'),
  ('flow-builder-v3-complete.sql','i','idx_automation_runs_status'),
  ('flow-builder-v3-complete.sql','i','idx_automations_org_status'),
  ('flow-builder-v3-complete.sql','i','idx_automations_trigger_type'),
  ('flow-builder-v3-complete.sql','i','idx_credentials_org'),
  ('pipeline-automation-rules.sql','t','public.automation_logs'),
  ('pipeline-automation-rules.sql','t','public.pipeline_automation_rules'),
  ('pipeline-automation-rules.sql','t','public.pipeline_stage_transitions'),
  ('pipeline-automation-rules.sql','f','public.get_active_automation_rules'),
  ('pipeline-automation-rules.sql','f','public.get_active_stage_transitions'),
  ('pipeline-automation-rules.sql','f','public.increment_automation_rule_counter'),
  ('pipeline-automation-rules.sql','f','public.increment_transition_counter'),
  ('pipeline-automation-rules.sql','f','public.update_pipeline_automation_counts'),
  ('pipeline-automation-rules.sql','c','pipelines.automation_rules_count'),
  ('pipeline-automation-rules.sql','c','pipelines.has_active_automations'),
  ('pipeline-automation-rules.sql','i','idx_automation_logs_org_date'),
  ('pipeline-automation-rules.sql','i','idx_automation_logs_rule'),
  ('pipeline-automation-rules.sql','i','idx_automation_rules_enabled'),
  ('pipeline-automation-rules.sql','i','idx_automation_rules_org'),
  ('pipeline-automation-rules.sql','i','idx_automation_rules_pipeline'),
  ('pipeline-automation-rules.sql','i','idx_automation_rules_source'),
  ('pipeline-automation-rules.sql','i','idx_stage_transitions_enabled'),
  ('pipeline-automation-rules.sql','i','idx_stage_transitions_org'),
  ('pipeline-automation-rules.sql','i','idx_stage_transitions_pipeline'),
  ('pipeline-automation-rules.sql','i','idx_stage_transitions_source'),
  ('shopify-enrichment.sql','t','public.contact_purchases'),
  ('shopify-enrichment.sql','t','public.contact_sessions'),
  ('shopify-enrichment.sql','f','public.calculate_contact_rfm'),
  ('shopify-enrichment.sql','c','contact_activities.occurred_at'),
  ('shopify-enrichment.sql','c','contact_activities.source'),
  ('shopify-enrichment.sql','c','contact_activities.source_id'),
  ('shopify-enrichment.sql','c','contact_activities.url'),
  ('shopify-enrichment.sql','c','contacts.days_since_last_order'),
  ('shopify-enrichment.sql','c','contacts.favorite_products'),
  ('shopify-enrichment.sql','c','contacts.first_order_at'),
  ('shopify-enrichment.sql','c','contacts.last_order_id'),
  ('shopify-enrichment.sql','c','contacts.last_order_number'),
  ('shopify-enrichment.sql','c','contacts.last_order_products'),
  ('shopify-enrichment.sql','c','contacts.last_order_value'),
  ('shopify-enrichment.sql','c','contacts.last_seen_at'),
  ('shopify-enrichment.sql','c','contacts.last_viewed_products'),
  ('shopify-enrichment.sql','c','contacts.order_frequency_days'),
  ('shopify-enrichment.sql','c','contacts.rfm_frequency_score'),
  ('shopify-enrichment.sql','c','contacts.rfm_monetary_score'),
  ('shopify-enrichment.sql','c','contacts.rfm_recency_score'),
  ('shopify-enrichment.sql','c','contacts.rfm_segment'),
  ('shopify-enrichment.sql','c','contacts.total_page_views'),
  ('shopify-enrichment.sql','c','shopify_stores.tracking_enabled'),
  ('shopify-enrichment.sql','c','shopify_stores.tracking_script_id'),
  ('shopify-enrichment.sql','i','idx_contact_activities_source'),
  ('shopify-enrichment.sql','i','idx_contact_activities_type'),
  ('shopify-enrichment.sql','i','idx_contact_purchases_contact'),
  ('shopify-enrichment.sql','i','idx_contact_purchases_date'),
  ('shopify-enrichment.sql','i','idx_contact_purchases_order'),
  ('shopify-enrichment.sql','i','idx_contact_purchases_org'),
  ('shopify-enrichment.sql','i','idx_contact_purchases_product'),
  ('shopify-enrichment.sql','i','idx_contact_sessions_contact'),
  ('shopify-enrichment.sql','i','idx_contact_sessions_org'),
  ('shopify-enrichment.sql','i','idx_contact_sessions_session'),
  ('shopify-enrichment.sql','i','idx_contact_sessions_started'),
  ('shopify-enrichment.sql','i','idx_contact_sessions_visitor'),
  ('shopify-enrichment.sql','i','idx_contacts_last_order'),
  ('shopify-enrichment.sql','i','idx_contacts_last_seen'),
  ('shopify-enrichment.sql','i','idx_contacts_rfm_segment'),
  ('shopify-enrichment.sql','i','idx_contacts_shopify_id'),
  ('store-analyses.sql','t','public.store_analyses'),
  ('store-analyses.sql','f','public.update_store_analyses_updated_at'),
  ('store-analyses.sql','i','idx_store_analyses_created'),
  ('store-analyses.sql','i','idx_store_analyses_org'),
  ('store-analyses.sql','i','idx_store_analyses_store'),
  ('whatsapp-cloud-ai-enable.sql','t','public.agent_traces'),
  ('whatsapp-cloud-ai-enable.sql','f','public.user_belongs_to_org'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_conversations.ai_agent_id'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_conversations.ai_debounce_until'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_conversations.ai_disabled_at'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_conversations.ai_disabled_reason'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_conversations.ai_enabled'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_conversations.ai_pending'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_conversations.assigned_agent_id'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_messages.ai_agent_id'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_messages.sender'),
  ('whatsapp-cloud-ai-enable.sql','c','whatsapp_cloud_messages.sent_by_bot'),
  ('whatsapp-cloud-ai-enable.sql','i','idx_agent_traces_conversation'),
  ('whatsapp-cloud-ai-enable.sql','i','idx_agent_traces_org_created'),
  ('whatsapp-cloud-ai-enable.sql','i','idx_wcc_ai_enabled'),
  ('whatsapp-connection-schema.sql','t','public.whatsapp_configs'),
  ('whatsapp-connection-schema.sql','t','public.whatsapp_connection_logs'),
  ('whatsapp-connection-schema.sql','t','public.whatsapp_instances'),
  ('whatsapp-connection-schema.sql','f','public.can_create_instance'),
  ('whatsapp-connection-schema.sql','f','public.count_active_instances'),
  ('whatsapp-connection-schema.sql','f','public.update_whatsapp_configs_updated_at'),
  ('whatsapp-connection-schema.sql','f','public.update_whatsapp_instances_updated_at'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_configs_org'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_configs_phone_number_id'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_connection_logs_created'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_connection_logs_event'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_connection_logs_instance'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_connection_logs_org'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_instances_org'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_instances_phone'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_instances_status'),
  ('whatsapp-connection-schema.sql','i','idx_whatsapp_instances_unique_id'),
  ('whatsapp-migration-fix.sql','t','public.whatsapp_connection_logs'),
  ('whatsapp-migration-fix.sql','f','public.count_active_instances'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.access_token'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.api_key'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.api_type'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.api_url'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.last_connected_at'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.last_message_at'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.messages_count'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.online_status'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.other'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.qr_code'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.qr_code_expires_at'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.session_data'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.session_expires_at'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.title'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.unique_id'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.waba_id'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.webhook_url'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.webhook_verified'),
  ('whatsapp-migration-fix.sql','c','whatsapp_instances.webhook_verify_token'),
  ('whatsapp-migration-fix.sql','i','idx_whatsapp_connection_logs_instance'),
  ('whatsapp-migration-fix.sql','i','idx_whatsapp_connection_logs_org'),
  ('whatsapp-migration-fix.sql','i','idx_whatsapp_instances_org'),
  ('whatsapp-migration-fix.sql','i','idx_whatsapp_instances_phone'),
  ('whatsapp-migration-fix.sql','i','idx_whatsapp_instances_status'),
  ('whatsapp-migration-fix.sql','i','idx_whatsapp_instances_unique_id'),
  ('whatsapp-quality-history.sql','t','public.whatsapp_quality_history'),
  ('whatsapp-quality-history.sql','f','public.get_quality_history'),
  ('whatsapp-quality-history.sql','f','public.increment_template_usage'),
  ('whatsapp-quality-history.sql','f','public.save_quality_history'),
  ('whatsapp-quality-history.sql','c','whatsapp_instances.messaging_limit_tier'),
  ('whatsapp-quality-history.sql','c','whatsapp_instances.quality_checked_at'),
  ('whatsapp-quality-history.sql','c','whatsapp_instances.quality_rating'),
  ('whatsapp-quality-history.sql','i','idx_quality_history_org'),
  ('whatsapp-quality-history.sql','i','idx_quality_history_phone'),
  ('whatsapp-quality-history.sql','i','idx_quality_history_rating')
),

verificado AS (
  SELECT e.arquivo, e.tipo, e.obj,
    CASE e.tipo
      WHEN 't' THEN EXISTS (
        SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = split_part(e.obj,'.',1)
          AND c.relname  = split_part(e.obj,'.',2)
          AND c.relkind IN ('r','p','v','m','f'))
      WHEN 'f' THEN EXISTS (
        SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = split_part(e.obj,'.',1)
          AND p.proname  = split_part(e.obj,'.',2))
      WHEN 'c' THEN EXISTS (
        SELECT 1 FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname = split_part(e.obj,'.',1)
          AND a.attname = split_part(e.obj,'.',2)
          AND a.attnum > 0 AND NOT a.attisdropped)
      WHEN 'i' THEN EXISTS (
        SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = e.obj AND c.relkind = 'i')
    END AS existe
  FROM esperado e
),
rotulo AS (
  SELECT *, CASE tipo WHEN 't' THEN 'tabela' WHEN 'f' THEN 'funcao'
                      WHEN 'c' THEN 'coluna' ELSE 'indice' END AS tipo_nome
  FROM verificado
),
-- um objeto pode ser criado por varios arquivos (IF NOT EXISTS repetido);
-- para o resumo e a lista de faltantes ele conta uma vez so
unico AS (
  SELECT DISTINCT tipo_nome, obj, existe FROM rotulo
)
SELECT * FROM (

  -- secao 1: resumo -----------------------------------------------------
  SELECT 1 AS ord, '1. RESUMO' AS secao, tipo_nome AS item,
         count(*) FILTER (WHERE NOT existe)::text || ' de ' || count(*)::text
           || ' faltando' AS status,
         CASE WHEN count(*) FILTER (WHERE NOT existe) = 0
              THEN 'ok' ELSE 'ver secao 3' END AS detalhe
  FROM unico GROUP BY tipo_nome

  UNION ALL
  SELECT 1, '1. RESUMO', 'TOTAL',
         count(*) FILTER (WHERE NOT existe)::text || ' de ' || count(*)::text
           || ' faltando',
         CASE WHEN count(*) FILTER (WHERE NOT existe) = 0
              THEN 'banco bate com o repo' ELSE 'divergencia' END
  FROM unico

  -- secao 2: status por migration ---------------------------------------
  UNION ALL
  SELECT 2, '2. MIGRATION', arquivo,
         CASE WHEN count(*) FILTER (WHERE NOT existe) = 0 THEN 'APLICADA'
              WHEN count(*) FILTER (WHERE existe)     = 0 THEN 'NAO_APLICADA'
              ELSE 'PARCIAL' END,
         count(*) FILTER (WHERE existe)::text || '/' || count(*)::text
           || ' objetos presentes'
  FROM rotulo GROUP BY arquivo

  -- secao 3: o que falta -------------------------------------------------
  UNION ALL
  SELECT 3, '3. FALTANDO', u.tipo_nome || ': ' || u.obj, 'AUSENTE',
         'declarado em ' || (
           SELECT string_agg(DISTINCT r.arquivo, ', ' ORDER BY r.arquivo)
           FROM rotulo r WHERE r.obj = u.obj AND r.tipo_nome = u.tipo_nome)
  FROM unico u WHERE NOT u.existe

) rel
ORDER BY ord,
         CASE WHEN status IN ('NAO_APLICADA','AUSENTE') THEN 0
              WHEN status = 'PARCIAL' THEN 1 ELSE 2 END,
         item;
-- LEITURA:
--   secao 2 e a resposta direta a pergunta "esta tudo feito?".
--     NAO_APLICADA = nenhum objeto do arquivo existe. Rode o arquivo.
--     PARCIAL      = o script abortou no meio (foi o caso da 001) OU
--                    parte dos objetos foi renomeada/removida depois.
--                    Abra o arquivo e compare com a secao 3.
--     APLICADA     = todos os objetos existem.
--   Duas ressalvas honestas, para nao te dar falso alarme:
--     a) objeto criado por uma migration e DROPADO de proposito por outra
--        mais nova aparece como faltando. Confira antes de re-rodar.
--     b) 8 migrations nao criam objeto nenhum e sao invisiveis aqui.
--        Sao exatamente as que falham em silencio — BLOCO 3.


-- ---------------------------------------------------------------------
-- BLOCO 3 - As 8 migrations que o BLOCO 2 nao enxerga
--
-- Nenhuma delas cria tabela, funcao, coluna ou indice: mexem em
-- publication, default, tipo de coluna, CHECK constraint, storage bucket
-- e RLS. Sao as que "rodam" sem deixar rastro, e as mais faceis de nunca
-- terem sido rodadas. Cada linha tem um teste proprio.
-- ---------------------------------------------------------------------
SELECT arquivo, CASE WHEN ok THEN 'APLICADA' ELSE 'NAO APLICADA' END AS status, o_que_verifica
FROM (
  SELECT '20260114_enable_inbox_realtime.sql' AS arquivo,
    (SELECT count(*) FROM pg_publication_tables
      WHERE pubname='supabase_realtime'
        AND tablename IN ('whatsapp_conversations','whatsapp_messages','whatsapp_instances')) = 3 AS ok,
    'as 3 tabelas do inbox legado na publication supabase_realtime' AS o_que_verifica
  UNION ALL SELECT '20260727_enable_cloud_inbox_realtime.sql',
    (SELECT count(*) FROM pg_publication_tables
      WHERE pubname='supabase_realtime'
        AND tablename IN ('whatsapp_cloud_conversations','whatsapp_cloud_messages')) = 2,
    'as 2 tabelas do inbox Cloud na publication  <<< RELEVANTE PARA O BUG DE REALTIME'
  UNION ALL SELECT '20260420_enable_sync_checkouts.sql',
    (SELECT count(*) FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid
      JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum
      WHERE c.relname='shopify_stores'
        AND a.attname IN ('sync_checkouts','sync_orders','sync_customers')
        AND pg_get_expr(d.adbin,d.adrelid)='true') = 3,
    'DEFAULT true nas 3 flags de sync de shopify_stores'
  UNION ALL SELECT '20260516_shopify_orders_order_number_text.sql',
    (SELECT data_type FROM information_schema.columns
      WHERE table_schema='public' AND table_name='shopify_orders'
        AND column_name='order_number') = 'text',
    'shopify_orders.order_number virou TEXT'
  UNION ALL SELECT '20260612_notifications_type_check_expand.sql',
    (SELECT count(*) FROM pg_constraint
      WHERE conname='notifications_type_check'
        AND pg_get_constraintdef(oid) LIKE '%whatsapp_ai_disabled%') > 0,
    'CHECK de notifications aceita whatsapp_ai_disabled'
  UNION ALL SELECT '20260727_notifications_media_handoff_type.sql',
    (SELECT count(*) FROM pg_constraint
      WHERE conname='notifications_type_check'
        AND pg_get_constraintdef(oid) LIKE '%whatsapp_ai_media_handoff%') > 0,
    'CHECK de notifications aceita whatsapp_ai_media_handoff (o tipo exclusivo desta)'
  UNION ALL SELECT '20260617_ai_sources_bucket.sql',
    (SELECT count(*) FROM storage.buckets WHERE id='ai-sources') > 0,
    'bucket ai-sources existe no storage'
  UNION ALL SELECT 'PARTE3_rls_e_dados.sql',
    (SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname='public' AND c.relrowsecurity
        AND c.relname IN ('google_ads_accounts','google_ads_campaigns','google_ads_ad_groups',
          'google_ads_keywords','google_ads_metrics','google_ads_search_terms','google_ads_products',
          'google_ads_product_metrics','meta_ads_accounts','meta_ads_campaigns','meta_ads_adsets',
          'meta_ads_ads','meta_ads_metrics','tiktok_ads_accounts','tiktok_ads_campaigns',
          'tiktok_ads_adgroups','tiktok_ads_metrics','credentials')) = 18,
    'RLS ligada nas 18 tabelas de ads/credentials'
) t ORDER BY ok, arquivo;
-- Se 20260727_enable_cloud_inbox_realtime aparecer NAO APLICADA, esta
-- e a causa do canal de mensagens nao entregar: a tabela nao publica
-- alteracao nenhuma, e nenhum erro e emitido para o client.
