api_version = "2026-01"

[[extensions]]
type = "web_pixel"
name = "Worder Pixel"
handle = "worder-pixel"
runtime_context = "strict"

[extensions.settings.fields.accountId]
name = "Account ID"
description = "Worder Account ID"
type = "single_line_text_field"

[extensions.settings.fields.storeId]
name = "Store ID"
description = "Worder Store ID"
type = "single_line_text_field"

[extensions.settings.fields.trackingEndpoint]
name = "Tracking Endpoint"
description = "URL do endpoint de tracking"
type = "single_line_text_field"
