api_version = "2026-01"

[[extensions]]
type = "web_pixel"
name = "Worder Pixel"
handle = "worder-pixel"
runtime_context = "strict"

  [extensions.settings]
    [[extensions.settings.fields]]
    key = "accountId"
    type = "single_line_text_field"
    name = "Account ID"
    description = "Worder Account ID"

    [[extensions.settings.fields]]
    key = "storeId"
    type = "single_line_text_field"
    name = "Store ID"
    description = "Worder Store ID"

    [[extensions.settings.fields]]
    key = "trackingEndpoint"
    type = "single_line_text_field"
    name = "Tracking Endpoint"
    description = "URL do endpoint de tracking"
