api_version = "2026-01"
type = "web_pixel_extension"
name = "Worder Pixel"
handle = "worder-pixel"
runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "enabled"

[settings]
type = "object"

[settings.fields.accountId]
name = "AccountId"
description = "Worder Account ID"
type = "single_line_text_field"
validations = []

[settings.fields.storeId]
name = "StoreId"
description = "Worder Store ID"
type = "single_line_text_field"
validations = []

[settings.fields.trackingEndpoint]
name = "TrackingEndpoint"
description = "URL do endpoint de tracking"
type = "single_line_text_field"
validations = []
