-- =============================================
-- WORDER: RESET ALL DATA (keep schema + auth)
-- Run this in Supabase SQL Editor
--
-- This script DELETES all business data but keeps:
--   - Database schema (tables, indexes, functions)
--   - Supabase auth users (auth.users)
--   - Organizations and profiles (your account)
--
-- After running: reconnect Shopify, reimport data.
-- =============================================

BEGIN;

-- ─── 1. WHATSAPP (most FK dependencies) ───
TRUNCATE TABLE IF EXISTS whatsapp_cloud_messages CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_cloud_conversations CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_ai_analytics CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_ai_interactions CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_ai_agents CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_ai_configs CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_csat_ratings CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_product_interests CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_payment_links CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_quality_history CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_notes CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_transfers CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_queue_agents CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_queues CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_campaign_analytics CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_campaign_logs CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_campaign_recipients CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_campaigns CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_flow_sessions CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_flows CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_chatbots CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_agent_assignments CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_agent_status CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_agents CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_contact_notes CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_contact_activities CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_conversation_tags CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_chat_tags CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_tags CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_quick_replies CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_messages CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_conversations CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_templates CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_segments CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_opt_status CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_business_hours CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_widget_config CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_connection_logs CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_configs CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_numbers CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_instances CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_business_accounts CASCADE;
TRUNCATE TABLE IF EXISTS whatsapp_accounts CASCADE;
TRUNCATE TABLE IF EXISTS phonebook_contacts CASCADE;
TRUNCATE TABLE IF EXISTS phonebooks CASCADE;

-- ─── 2. EMAIL / CAMPAIGNS ───
TRUNCATE TABLE IF EXISTS email_clicks CASCADE;
TRUNCATE TABLE IF EXISTS email_sends CASCADE;
TRUNCATE TABLE IF EXISTS campaign_metrics CASCADE;
TRUNCATE TABLE IF EXISTS flow_metrics CASCADE;
TRUNCATE TABLE IF EXISTS email_campaigns CASCADE;
TRUNCATE TABLE IF EXISTS email_templates CASCADE;
TRUNCATE TABLE IF EXISTS email_domains CASCADE;
TRUNCATE TABLE IF EXISTS email_configs CASCADE;
TRUNCATE TABLE IF EXISTS saved_block_versions CASCADE;
TRUNCATE TABLE IF EXISTS saved_blocks CASCADE;
TRUNCATE TABLE IF EXISTS coupons CASCADE;
TRUNCATE TABLE IF EXISTS product_feeds CASCADE;
TRUNCATE TABLE IF EXISTS brand_kits CASCADE;
TRUNCATE TABLE IF EXISTS sms_campaigns CASCADE;
TRUNCATE TABLE IF EXISTS marketing_campaigns CASCADE;

-- ─── 3. AUTOMATIONS / FLOWS ───
TRUNCATE TABLE IF EXISTS automation_execution_logs CASCADE;
TRUNCATE TABLE IF EXISTS automation_executions CASCADE;
TRUNCATE TABLE IF EXISTS automation_run_steps CASCADE;
TRUNCATE TABLE IF EXISTS automation_runs CASCADE;
TRUNCATE TABLE IF EXISTS automation_queue CASCADE;
TRUNCATE TABLE IF EXISTS automation_pending_steps CASCADE;
TRUNCATE TABLE IF EXISTS scheduled_automation_jobs CASCADE;
TRUNCATE TABLE IF EXISTS automation_logs CASCADE;
TRUNCATE TABLE IF EXISTS automation_webhooks CASCADE;
TRUNCATE TABLE IF EXISTS automation_rules CASCADE;
TRUNCATE TABLE IF EXISTS automation_versions CASCADE;
TRUNCATE TABLE IF EXISTS automation_triggers CASCADE;
TRUNCATE TABLE IF EXISTS playbook_runs CASCADE;
TRUNCATE TABLE IF EXISTS automation_playbooks CASCADE;
TRUNCATE TABLE IF EXISTS automations CASCADE;
TRUNCATE TABLE IF EXISTS automation_templates CASCADE;
TRUNCATE TABLE IF EXISTS event_logs CASCADE;
TRUNCATE TABLE IF EXISTS flow_webhooks CASCADE;
TRUNCATE TABLE IF EXISTS flow_webhook_logs CASCADE;
TRUNCATE TABLE IF EXISTS scheduled_executions CASCADE;
TRUNCATE TABLE IF EXISTS node_schemas CASCADE;

-- ─── 4. CONTACTS / AUDIENCE ───
TRUNCATE TABLE IF EXISTS contact_invoices CASCADE;
TRUNCATE TABLE IF EXISTS contact_purchases CASCADE;
TRUNCATE TABLE IF EXISTS contact_sessions CASCADE;
TRUNCATE TABLE IF EXISTS contact_attachments CASCADE;
TRUNCATE TABLE IF EXISTS contact_comments CASCADE;
TRUNCATE TABLE IF EXISTS contact_activities CASCADE;
TRUNCATE TABLE IF EXISTS contact_tags CASCADE;
TRUNCATE TABLE IF EXISTS contact_events CASCADE;
TRUNCATE TABLE IF EXISTS contact_external_mappings CASCADE;
TRUNCATE TABLE IF EXISTS contact_rfm_scores CASCADE;
TRUNCATE TABLE IF EXISTS customer_rfm_scores CASCADE;
TRUNCATE TABLE IF EXISTS segment_members CASCADE;
TRUNCATE TABLE IF EXISTS segment_memberships_snapshot CASCADE;
TRUNCATE TABLE IF EXISTS list_contacts CASCADE;
TRUNCATE TABLE IF EXISTS lists CASCADE;
TRUNCATE TABLE IF EXISTS customer_segments CASCADE;
TRUNCATE TABLE IF EXISTS contacts CASCADE;

-- ─── 5. CRM / DEALS ───
TRUNCATE TABLE IF EXISTS deal_stage_transitions CASCADE;
TRUNCATE TABLE IF EXISTS deal_stage_history CASCADE;
TRUNCATE TABLE IF EXISTS deal_activities CASCADE;
TRUNCATE TABLE IF EXISTS deals CASCADE;
TRUNCATE TABLE IF EXISTS pipeline_automation_rules CASCADE;
TRUNCATE TABLE IF EXISTS pipeline_stage_transitions CASCADE;
TRUNCATE TABLE IF EXISTS pipeline_stages CASCADE;
TRUNCATE TABLE IF EXISTS pipelines CASCADE;
TRUNCATE TABLE IF EXISTS lead_distribution_logs CASCADE;
TRUNCATE TABLE IF EXISTS lead_distribution_rules CASCADE;
TRUNCATE TABLE IF EXISTS lead_scores CASCADE;
TRUNCATE TABLE IF EXISTS crm_form_events CASCADE;
TRUNCATE TABLE IF EXISTS crm_form_event_logs CASCADE;
TRUNCATE TABLE IF EXISTS crm_form_submissions CASCADE;
TRUNCATE TABLE IF EXISTS crm_form_fields CASCADE;
TRUNCATE TABLE IF EXISTS crm_forms CASCADE;
TRUNCATE TABLE IF EXISTS crm_automation_rules CASCADE;
TRUNCATE TABLE IF EXISTS crm_analytics_cache CASCADE;
TRUNCATE TABLE IF EXISTS nps_responses CASCADE;
TRUNCATE TABLE IF EXISTS nps_surveys CASCADE;
TRUNCATE TABLE IF EXISTS sla_metrics CASCADE;
TRUNCATE TABLE IF EXISTS sla_configs CASCADE;
TRUNCATE TABLE IF EXISTS chat_templates CASCADE;
TRUNCATE TABLE IF EXISTS tasks CASCADE;
TRUNCATE TABLE IF EXISTS task_reminders CASCADE;
TRUNCATE TABLE IF EXISTS tickets CASCADE;
TRUNCATE TABLE IF EXISTS ticket_comments CASCADE;
TRUNCATE TABLE IF EXISTS ticket_history CASCADE;

-- ─── 6. SHOPIFY / COMMERCE ───
TRUNCATE TABLE IF EXISTS shopify_webhook_events CASCADE;
TRUNCATE TABLE IF EXISTS shopify_webhook_log CASCADE;
TRUNCATE TABLE IF EXISTS shopify_sync_logs CASCADE;
TRUNCATE TABLE IF EXISTS shopify_import_jobs CASCADE;
TRUNCATE TABLE IF EXISTS shopify_automation_logs CASCADE;
TRUNCATE TABLE IF EXISTS shopify_transition_rules CASCADE;
TRUNCATE TABLE IF EXISTS shopify_rfm_scores CASCADE;
TRUNCATE TABLE IF EXISTS shopify_rfm_summary CASCADE;
TRUNCATE TABLE IF EXISTS shopify_cohort_analysis CASCADE;
TRUNCATE TABLE IF EXISTS shopify_variants CASCADE;
TRUNCATE TABLE IF EXISTS shopify_products_cache CASCADE;
TRUNCATE TABLE IF EXISTS shopify_checkouts CASCADE;
TRUNCATE TABLE IF EXISTS shopify_orders CASCADE;
TRUNCATE TABLE IF EXISTS shopify_customers CASCADE;
TRUNCATE TABLE IF EXISTS shopify_products CASCADE;
TRUNCATE TABLE IF EXISTS shopify_sync_config CASCADE;
TRUNCATE TABLE IF EXISTS shopify_stores CASCADE;
TRUNCATE TABLE IF EXISTS orders CASCADE;
TRUNCATE TABLE IF EXISTS abandoned_carts CASCADE;
TRUNCATE TABLE IF EXISTS recovery_items CASCADE;
TRUNCATE TABLE IF EXISTS recovery_carts CASCADE;
TRUNCATE TABLE IF EXISTS product_costs CASCADE;
TRUNCATE TABLE IF EXISTS custom_fees CASCADE;
TRUNCATE TABLE IF EXISTS exchange_rates CASCADE;
TRUNCATE TABLE IF EXISTS organization_tax_settings CASCADE;
TRUNCATE TABLE IF EXISTS products CASCADE;

-- ─── 7. ADS (Meta, Google, TikTok) ───
TRUNCATE TABLE IF EXISTS meta_insights CASCADE;
TRUNCATE TABLE IF EXISTS meta_ads CASCADE;
TRUNCATE TABLE IF EXISTS meta_adsets CASCADE;
TRUNCATE TABLE IF EXISTS meta_campaigns CASCADE;
TRUNCATE TABLE IF EXISTS meta_accounts CASCADE;
TRUNCATE TABLE IF EXISTS meta_ads_metrics CASCADE;
TRUNCATE TABLE IF EXISTS meta_ads_ads CASCADE;
TRUNCATE TABLE IF EXISTS meta_ads_adsets CASCADE;
TRUNCATE TABLE IF EXISTS meta_ads_campaigns CASCADE;
TRUNCATE TABLE IF EXISTS meta_ads_accounts CASCADE;
TRUNCATE TABLE IF EXISTS meta_integrations CASCADE;
TRUNCATE TABLE IF EXISTS meta_pixels CASCADE;
TRUNCATE TABLE IF EXISTS google_ads_product_metrics CASCADE;
TRUNCATE TABLE IF EXISTS google_ads_products CASCADE;
TRUNCATE TABLE IF EXISTS google_ads_search_terms CASCADE;
TRUNCATE TABLE IF EXISTS google_ads_keywords CASCADE;
TRUNCATE TABLE IF EXISTS google_ads_metrics CASCADE;
TRUNCATE TABLE IF EXISTS google_ads_ad_groups CASCADE;
TRUNCATE TABLE IF EXISTS google_ads_campaigns CASCADE;
TRUNCATE TABLE IF EXISTS google_ads_accounts CASCADE;
TRUNCATE TABLE IF EXISTS google_ad_accounts CASCADE;
TRUNCATE TABLE IF EXISTS google_accounts CASCADE;
TRUNCATE TABLE IF EXISTS tiktok_ads_metrics CASCADE;
TRUNCATE TABLE IF EXISTS tiktok_ads_adgroups CASCADE;
TRUNCATE TABLE IF EXISTS tiktok_ads_campaigns CASCADE;
TRUNCATE TABLE IF EXISTS tiktok_ads_accounts CASCADE;
TRUNCATE TABLE IF EXISTS tiktok_metrics CASCADE;
TRUNCATE TABLE IF EXISTS tiktok_adgroups CASCADE;
TRUNCATE TABLE IF EXISTS tiktok_campaigns CASCADE;
TRUNCATE TABLE IF EXISTS tiktok_accounts CASCADE;
TRUNCATE TABLE IF EXISTS tiktok_ad_accounts CASCADE;

-- ─── 8. AI / KNOWLEDGE ───
TRUNCATE TABLE IF EXISTS ai_usage_logs CASCADE;
TRUNCATE TABLE IF EXISTS ai_message_logs CASCADE;
TRUNCATE TABLE IF EXISTS ai_agent_actions CASCADE;
TRUNCATE TABLE IF EXISTS ai_agent_integrations CASCADE;
TRUNCATE TABLE IF EXISTS ai_agent_configs CASCADE;
TRUNCATE TABLE IF EXISTS ai_agent_chunks CASCADE;
TRUNCATE TABLE IF EXISTS ai_agent_sources CASCADE;
TRUNCATE TABLE IF EXISTS ai_agents CASCADE;
TRUNCATE TABLE IF EXISTS ai_knowledge_chunks CASCADE;
TRUNCATE TABLE IF EXISTS ai_knowledge_sources CASCADE;
TRUNCATE TABLE IF EXISTS ai_model_pricing CASCADE;
TRUNCATE TABLE IF EXISTS ai_models CASCADE;
TRUNCATE TABLE IF EXISTS knowledge_documents CASCADE;
TRUNCATE TABLE IF EXISTS knowledge_bases CASCADE;

-- ─── 9. INTEGRATIONS / CREDENTIALS ───
TRUNCATE TABLE IF EXISTS integration_health_logs CASCADE;
TRUNCATE TABLE IF EXISTS integration_sync_logs CASCADE;
TRUNCATE TABLE IF EXISTS installed_integrations CASCADE;
TRUNCATE TABLE IF EXISTS integrations CASCADE;
TRUNCATE TABLE IF EXISTS integration_categories CASCADE;
TRUNCATE TABLE IF EXISTS credentials CASCADE;
TRUNCATE TABLE IF EXISTS webhook_test_logs CASCADE;
TRUNCATE TABLE IF EXISTS webhook_events CASCADE;
TRUNCATE TABLE IF EXISTS webhooks CASCADE;
TRUNCATE TABLE IF EXISTS api_keys CASCADE;
TRUNCATE TABLE IF EXISTS organization_api_keys CASCADE;
TRUNCATE TABLE IF EXISTS oauth_states CASCADE;
TRUNCATE TABLE IF EXISTS klaviyo_lists CASCADE;
TRUNCATE TABLE IF EXISTS klaviyo_accounts CASCADE;
TRUNCATE TABLE IF EXISTS hotmart_accounts CASCADE;
TRUNCATE TABLE IF EXISTS woocommerce_stores CASCADE;
TRUNCATE TABLE IF EXISTS evolution_instances CASCADE;

-- ─── 10. INSTAGRAM ───
TRUNCATE TABLE IF EXISTS instagram_messages CASCADE;
TRUNCATE TABLE IF EXISTS instagram_conversations CASCADE;
TRUNCATE TABLE IF EXISTS instagram_quick_replies CASCADE;
TRUNCATE TABLE IF EXISTS instagram_contacts CASCADE;
TRUNCATE TABLE IF EXISTS instagram_accounts CASCADE;

-- ─── 11. ANALYTICS / LOGS / MISC ───
TRUNCATE TABLE IF EXISTS daily_metrics CASCADE;
TRUNCATE TABLE IF EXISTS visitor_sessions CASCADE;
TRUNCATE TABLE IF EXISTS store_analyses CASCADE;
TRUNCATE TABLE IF EXISTS tracking_events CASCADE;
TRUNCATE TABLE IF EXISTS attribution_touchpoints CASCADE;
TRUNCATE TABLE IF EXISTS activity_log CASCADE;
TRUNCATE TABLE IF EXISTS activity_logs CASCADE;
TRUNCATE TABLE IF EXISTS audit_logs CASCADE;
TRUNCATE TABLE IF EXISTS notifications CASCADE;
TRUNCATE TABLE IF EXISTS notification_preferences CASCADE;
TRUNCATE TABLE IF EXISTS reports CASCADE;
TRUNCATE TABLE IF EXISTS media_files CASCADE;
TRUNCATE TABLE IF EXISTS comment_mentions CASCADE;
TRUNCATE TABLE IF EXISTS lead_routing_rules CASCADE;
TRUNCATE TABLE IF EXISTS forms CASCADE;
TRUNCATE TABLE IF EXISTS tags CASCADE;
TRUNCATE TABLE IF EXISTS stores CASCADE;
TRUNCATE TABLE IF EXISTS agents CASCADE;
TRUNCATE TABLE IF EXISTS messages CASCADE;
TRUNCATE TABLE IF EXISTS activities CASCADE;
TRUNCATE TABLE IF EXISTS queue_settings CASCADE;
TRUNCATE TABLE IF EXISTS queue_items CASCADE;
TRUNCATE TABLE IF EXISTS agent_permissions CASCADE;
TRUNCATE TABLE IF EXISTS scheduled_messages CASCADE;

-- ─── 12. LGPD / BILLING ───
TRUNCATE TABLE IF EXISTS lgpd_data_requests CASCADE;
TRUNCATE TABLE IF EXISTS lgpd_consents CASCADE;
TRUNCATE TABLE IF EXISTS lgpd_retention_policies CASCADE;
TRUNCATE TABLE IF EXISTS billing_invoices CASCADE;
TRUNCATE TABLE IF EXISTS billing_subscriptions CASCADE;

-- ─── 13. HELP / FAQ ───
TRUNCATE TABLE IF EXISTS faq_items CASCADE;
TRUNCATE TABLE IF EXISTS help_articles CASCADE;
TRUNCATE TABLE IF EXISTS help_categories CASCADE;

COMMIT;

-- =============================================
-- VERIFY: Count remaining rows in key tables
-- =============================================
SELECT 'organizations' as tbl, count(*) FROM organizations
UNION ALL SELECT 'profiles', count(*) FROM profiles
UNION ALL SELECT 'organization_members', count(*) FROM organization_members
UNION ALL SELECT 'contacts', count(*) FROM contacts
UNION ALL SELECT 'shopify_stores', count(*) FROM shopify_stores
UNION ALL SELECT 'email_campaigns', count(*) FROM email_campaigns
UNION ALL SELECT 'automations', count(*) FROM automations
ORDER BY tbl;
